/*
 * Copyright © 2025-present Jiangsu Qiantong Technology Co., Ltd.
 *
 * This file is part of qData Data Middle Platform (Open Source Edition).
 *
 * qData is licensed under Apache License 2.0 with additional qData terms.
 * You may use qData for commercial purposes, but you may not remove, hide,
 * modify, or replace the qData logo, copyright notices, license notices,
 * or attribution information without a separate commercial license.
 *
 * White-label use, OEM distribution, rebranding, or presenting qData as
 * another product requires separate commercial authorization from
 * Jiangsu Qiantong Technology Co., Ltd.
 *
 * Business License: https://community.qdata.tech/business/policy.html
 * See the LICENSE file in the project root for full license information.
 */

package tech.qiantong.qdata.module.da.dal.dataobject.asset;

import com.baomidou.mybatisplus.annotation.*;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;
import tech.qiantong.qdata.common.core.domain.BaseEntity;
import tech.qiantong.qdata.module.da.controller.admin.assetchild.api.vo.DaAssetApiRespVO;
import tech.qiantong.qdata.module.da.controller.admin.assetchild.theme.vo.DaAssetThemeRelRespVO;

import java.util.List;

/**
 * Data Asset DO - DA_ASSET
 *
 * @author lhs
 * @date 2025-01-21
 */
@Data
@TableName(value = "DA_ASSET")
// Used for auto-increment primary keys in Oracle, PostgreSQL, Kingbase, DB2, H2 databases. Not needed for MySQL and similar databases.
// @KeySequence("DA_ASSET_seq")
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
public class DaAssetDO extends BaseEntity {
    @TableField(exist = false)
    private static final long serialVersionUID = 1L;

    /** ID */
    @TableId(type = IdType.AUTO)
    private Long id;

    /** Asset Name */
    private String name;

    @Schema(description = "资产类型", example = "")
    private String type;

    /** Category Code */
    private String catCode;

    @TableField(exist = false)
    private String catName;

    /**
     * Table type; 1: Detail table 2: Summary table 3: Dimension table 4: Application table
     */
    @Schema(name = "表类型 1:明细表 2:汇总表 3:维度表 4:应用表")
    private String tableType;
    /**
     * Data warehouse layer ID
     */
    @Schema(name = "数仓分层id ")
    private Long dataLayerId;
    /**
     * Business category ID; only has value when table type is non-application table
     */
    @Schema(name = "业务分类id 只有表类型为非应用表是才有值")
    private Long businessCategoryId;
    /**
     * Business category hierarchy code
     */
    @Schema(name = "业务分类层级编码 ")
    private String businessCategoryCode;
    /**
     * Data domain ID; only has value when table type is non-application table
     */
    @Schema(name = "数据分域id 只有表类型为非应用表是才有值")
    private Long dataDomainId;
    /**
     * Theme domain ID (theme planning); only has value when table type is application table
     */
    @Schema(name = "所属主题id（主题规划） 只有表类型为应用表是才有值")
    private Long themeDomainId;
    /**
     * Theme domain hierarchy code
     */
    @Schema(name = "所属主题层级编码 ")
    private String themeDomainCode;
    /**
     * Table name case; 1: uppercase 2: lowercase
     */
    @Schema(description = "表名大小写 1：大写 2：小写")
    private String tableCase;

    /**
     * Metadata table ID
     */
    @Schema(description = "元数据表id")
    private Long tableId;

    /** Whether the asset is from an application or self-generated by the project. 0: applied, 1: self-created */
    @TableField(exist = false)
    private String sourceType;

    @TableField(exist = false)
    private List<DaAssetThemeRelRespVO> daAssetThemeRelList;

    /** Datasource ID */
    private Long datasourceId;

    @TableField(exist = false)
    private String datasourceName;

    @TableField(exist = false)
    private String datasourceIp;

    @TableField(exist = false)
    private String datasourceType;

    /** Table Name */
    private String tableName;

    /** Table Comment */
    private String tableComment;

    /** Data Count */
    private Long dataCount;

    /** Field Count */
    private Long fieldCount;

    /** Source; 1: data discovery; 2: data model; */
    private String source;

    /** Status */
    private String status;

    /** Description */
    private String description;

    /** Valid Flag */
    private Boolean validFlag;

    /** Delete Flag */
    @TableLogic
    private Boolean delFlag;

    // api
    @TableField(exist = false)
    private DaAssetApiRespVO daAssetApi;
//    // api
//    @TableField(exist = false)
//    private List<DaAssetApiParamRespVO> daAssetApiParamList;
//
//    /**
//     * Vector
//     */
//    @TableField(exist = false)
//    private DaAssetGeoRespVO daAssetGeo;
//
//    /**
//     * Geospatial Service
//     */
//    @TableField(exist = false)
//    private DaAssetGisRespVO daAssetGis;
//
//    /**
//     * Video Data
//     */
//    @TableField(exist = false)
//    private DaAssetVideoRespVO daAssetVideo;

    @Schema(description = "项目id", example = "")
    @TableField(exist = false)
    private Long projectId;

    @Schema(description = "项目编码", example = "")
    @TableField(exist = false)
    private String projectCode;
    /** Creation Type */
    private String createType;

    @TableField(exist = false)
    private String tags;

    @Schema(name = "数仓分层名称")
    @TableField(exist = false)
    private String dataLayerName;

    @Schema(name = "数仓分层英文缩写")
    @TableField(exist = false)
    private String dataLayerEngName;

    @Schema(name = "业务名称")
    @TableField(exist = false)
    private String businessCategoryName;

    @Schema(name = "业务英文缩写")
    @TableField(exist = false)
    private String businessCategoryEngName;

    @Schema(name = "数据分域名称")
    @TableField(exist = false)
    private String dataDomainName;

    @Schema(name = "数据分域英文缩写")
    @TableField(exist = false)
    private String dataDomainEngName;

    @Schema(name = "所属主题名称")
    @TableField(exist = false)
    private String themeDomainName;

    @Schema(name = "所属主题英文缩写")
    @TableField(exist = false)
    private String themeDomainEngName;

    @Schema(name = "创建人联系电话")
    @TableField(exist = false)
    private String createUserPhoneNumber;


    @Schema(name = "修改人联系电话")
    @TableField(exist = false)
    private String updateUserPhoneNumber;
}
