# Copyright (c) 2026 Jiangsu Qiantong Technology Co., Ltd.
#  *
# Software Name: qData Data Middle Platform (Commercial Edition)
# Software Copyright Registration No. 16069171
#  *
# [RIGHTS AND LICENSE STATEMENT]
# This file contains non-public commercial source code of which Jiangsu Qiantong
# Technology Co., Ltd. lawfully possesses complete intellectual property rights.
#  *
# Access and use are limited to entities or individuals who have signed a valid
# commercial license agreement, within the scope stipulated in the agreement.
# The "accessibility" of this source code is premised on lawful authorization
# and does not constitute any form of transfer of intellectual property rights
# or implied licensing.
#  *
# [PROHIBITIONS]
# Unless explicitly agreed in the license agreement, the following acts in any
# form are strictly prohibited:
# 1. Copying, disseminating, disclosing, selling, renting, or redistributing
# this source code;
# 2. Providing the software's functionality to third parties via SaaS, PaaS,
# cloud hosting, or other means;
# 3. Using this software or its derivative versions to develop products that
# compete with the Right Holder;
# 4. Providing or displaying this source code or related technical information
# to unauthorized third parties;
# 5. Tampering with, circumventing, or destroying copyright notices, license
# verifications, or other technical protection measures.
#  *
# [LEGAL LIABILITY]
# Any unauthorized use constitutes an infringement of trade secrets and
# intellectual property rights.
#  *
# The Right Holder will strictly pursue liability for breach of contract and
# infringement in accordance with the commercial agreement and laws such as
# the "Copyright Law of the People's Republic of China" and the "Anti-Unfair
# Competition Law".
#  *
# ============================================================================
#  *
# Copyright (c) 2026 江苏千桐科技有限公司
#  *
# 软件名称：qData 数据中台（商业版） | 软著登字第16069171号
#  *
# 【权利与授权声明】
# 本文件属于江苏千桐科技有限公司依法享有完全知识产权的非公开商业源代码。
# 仅限已签署有效商业授权合同的单位或个人在约定范围内查阅和使用。
# 源代码的“可访问性”均以合法授权为前提，不构成任何形式的知识产权转让或默示授权。
#  *
# 【禁止事项】
# 除授权合同明确约定外，严禁任何形式的：
# 1. 复制、传播、披露、出售、出租或再分发本源代码；
# 2. 通过 SaaS、PaaS、云托管等方式向第三方提供本软件功能；
# 3. 将本软件或其衍生版本用于开发与权利人构成竞争的产品；
# 4. 向未授权第三方提供或展示本源代码或相关技术信息；
# 5. 篡改、规避或破坏版权标识、授权校验及其他技术保护措施。
#  *
# 【法律责任】
# 任何未经授权的利用行为，均构成对商业秘密及知识产权的侵害。
# 权利人将依据商业合同及《中华人民共和国著作权法》《反不正当竞争法》
# 等法律法规，严厉追究违约与侵权责任。

# 主数据源选择
datasource:
  type: ${DB_TYPE}

# Spring配置
spring:
  # redis 配置
  data:
    redis:
      # 地址
      host: redis
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      # 密码
      password: J98%FHF#9h@e88h9fre9
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
  datasource:
    druid:
      stat-view-servlet:
        # 是否启用Druid的监控统计功能
        enabled: false
        # 访问Druid监控页面的用户名
        loginUsername: qdata
        # 访问Druid监控页面的密码
        loginPassword: 123456
    dynamic:
      druid:
        # 连接池初始化时创建的连接数量
        initial-size: 5
        # 连接池中最小空闲连接数
        min-idle: 5
        # 连接池中最大活动连接数
        maxActive: 20
        # 连接池等待连接的最长时间（毫秒）
        maxWait: 60000
        # 数据库连接超时时间（毫秒）
        connectTimeout: 30000
        # Socket超时时间（毫秒）
        socketTimeout: 60000
        # 空闲连接的检测周期（毫秒）
        timeBetweenEvictionRunsMillis: 60000
        # 最小空闲连接的存活时间（毫秒）
        minEvictableIdleTimeMillis: 300000
        # 用于检测连接是否有效的SQL语句
        validationQuery: SELECT 1 FROM DUAL
        # 是否在空闲时检测连接的有效性
        testWhileIdle: true
        # 借用连接时是否测试连接的有效性
        testOnBorrow: false
        # 归还连接时是否测试连接的有效性
        testOnReturn: false
        # 是否打开连接池的PreparedStatement缓存
        poolPreparedStatements: true
        # 每个连接池的PreparedStatement缓存上限
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置Druid的过滤器
        filters: stat,slf4j
        # Druid连接属性配置
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        # 主库数据源配置
        master:
          # 动态加载的配置属性
          driver-class-name: ${${datasource.type}.driver-class-name}
          url: ${${datasource.type}.url}
          username: ${${datasource.type}.username}
          password: ${${datasource.type}.password}

# MySQL配置文件
mysql:
  # JDBC驱动类名
  driver-class-name: com.mysql.cj.jdbc.Driver
  # 主库JDBC连接URL
  url: jdbc:mysql://mysql:3306/qdata?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
  # 主库用户名
  username: root
  # 主库密码
  password: o5KjnPYxswsiURZHCPwd

# 达梦配置文件
dm8:
  # JDBC驱动类名
  driver-class-name: dm.jdbc.driver.DmDriver
  # 主库JDBC连接URL
  url: jdbc:dm://dm8:5236/QDATA?STU&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&schema=QDATA&serverTimezone=Asia/Shanghai
  # 主库用户名
  username: QDATA
  # 主库密码
  password: s2LKr6LMQxVDTQx

