CREATE TABLE "QDATA"."QUARTZ_JOB"
(
    "JOB_ID" BIGINT IDENTITY(1,1) NOT NULL,
    "JOB_NAME" VARCHAR(64) DEFAULT '' NOT NULL,
    "JOB_GROUP" VARCHAR(64) DEFAULT 'DEFAULT' NOT NULL,
    "INVOKE_TARGET" VARCHAR(500) NOT NULL,
    "CRON_EXPRESSION" VARCHAR(255) DEFAULT '' NULL,
    "MISFIRE_POLICY" VARCHAR(20) DEFAULT '3' NULL,
    "CONCURRENT" CHAR(1) DEFAULT '1' NULL,
    "EXECUTION_TYPE" VARCHAR(32) NULL,
    "STATUS" CHAR(1) DEFAULT '0' NULL,
    "CREATE_BY" VARCHAR(64) DEFAULT '' NULL,
    "CREATE_TIME" TIMESTAMP(0) NULL,
    "UPDATE_BY" VARCHAR(64) DEFAULT '' NULL,
    "UPDATE_TIME" TIMESTAMP(0) NULL,
    "REMARK" VARCHAR(500) DEFAULT '' NULL,
    CONSTRAINT "PK_QUARTZ_JOB" PRIMARY KEY("JOB_ID")
);

COMMENT ON TABLE "QDATA"."QUARTZ_JOB" IS 'Quartz业务调度任务表';
COMMENT ON TABLE "QDATA"."JOB_ID" IS '任务ID';
COMMENT ON TABLE "QDATA"."JOB_NAME" IS '任务名称';
COMMENT ON TABLE "QDATA"."JOB_GROUP" IS '任务组名';
COMMENT ON TABLE "QDATA"."INVOKE_TARGET" IS '调用目标字符串';
COMMENT ON TABLE "QDATA"."CRON_EXPRESSION" IS 'cron执行表达式';
COMMENT ON TABLE "QDATA"."MISFIRE_POLICY" IS '计划执行错误策略（1立即执行 2执行一次 3放弃执行）';
COMMENT ON TABLE "QDATA"."CONCURRENT" IS '是否并发执行（0允许 1禁止）';
COMMENT ON TABLE "QDATA"."EXECUTION_TYPE" IS '执行类型 PARALLEL（并行）、SERIAL_WAIT（串行等待）、SERIAL_DISCARD（串行丢弃）、SERIAL_PRIORITY（串行优先级）';
COMMENT ON TABLE "QDATA"."STATUS" IS '状态（0正常 1暂停）';
COMMENT ON TABLE "QDATA"."CREATE_BY" IS '创建者';
COMMENT ON TABLE "QDATA"."CREATE_TIME" IS '创建时间';
COMMENT ON TABLE "QDATA"."UPDATE_BY" IS '更新者';
COMMENT ON TABLE "QDATA"."UPDATE_TIME" IS '更新时间';
COMMENT ON TABLE "QDATA"."REMARK" IS '备注信息';

CREATE TABLE "QDATA"."QUARTZ_JOB_LOG"
(
    "JOB_LOG_ID"    BIGINT IDENTITY(1,1) NOT NULL,
    "JOB_NAME"      VARCHAR(64) NOT NULL,
    "JOB_GROUP"     VARCHAR(64) NOT NULL,
    "INVOKE_TARGET" VARCHAR(500) NOT NULL,
    "JOB_MESSAGE"   VARCHAR(500),
    "STATUS"        CHAR(1) DEFAULT '0',
    "EXCEPTION_INFO" VARCHAR(2000) DEFAULT '',
    "CREATE_TIME"   TIMESTAMP(0),
    CONSTRAINT "PK_QUARTZ_JOB_LOG" PRIMARY KEY ("JOB_LOG_ID")
);

COMMENT ON TABLE "QDATA"."QUARTZ_JOB_LOG" IS 'Quartz业务调度任务日志表';
COMMENT ON TABLE "QDATA"."JOB_LOG_ID" IS '任务日志ID';
COMMENT ON TABLE "QDATA"."JOB_NAME" IS '任务名称';
COMMENT ON TABLE "QDATA"."JOB_GROUP" IS '任务组名';
COMMENT ON TABLE "QDATA"."INVOKE_TARGET" IS '调用目标字符串';
COMMENT ON TABLE "QDATA"."JOB_MESSAGE" IS '日志信息';
COMMENT ON TABLE "QDATA"."STATUS" IS '执行状态（0正常 1失败）';
COMMENT ON TABLE "QDATA"."EXCEPTION_INFO" IS '异常信息';
COMMENT ON TABLE "QDATA"."CREATE_TIME" IS '创建时间';

ALTER TABLE "QDATA"."DPP_ETL_TASK" ADD (
    "QUARTZ_ID" BIGINT NULL,
    "SCHEDULER" VARCHAR(32) NULL,
    "ACTUATOR"  VARCHAR(32) NULL
);
COMMENT ON COLUMN "QDATA"."DPP_ETL_TASK"."QUARTZ_ID" IS 'Quartz调度任务ID';
COMMENT ON COLUMN "QDATA"."DPP_ETL_TASK"."SCHEDULER" IS '调度器';
COMMENT ON COLUMN "QDATA"."DPP_ETL_TASK"."ACTUATOR" IS '执行器';

ALTER TABLE "QDATA"."DPP_ETL_SCHEDULER" ADD "QUARTZ_ID" BIGINT NULL;
COMMENT ON COLUMN "QDATA"."DPP_ETL_SCHEDULER"."QUARTZ_ID" IS 'Quartz调度任务ID';

ALTER TABLE "QDATA"."MC_TASK_SCHEDULER" ADD "SCHEDULER" VARCHAR(32) NULL;
COMMENT ON COLUMN "QDATA"."MC_TASK_SCHEDULER"."SCHEDULER" IS '调度引擎';