UPDATE "QDATA"."ATT_CLEAN_RULE"	SET VALID_FLAG='1' WHERE CODE='008';
UPDATE "QDATA"."ATT_CLEAN_RULE"	SET VALID_FLAG='1' WHERE CODE='011';
UPDATE "QDATA"."ATT_CLEAN_RULE"	SET VALID_FLAG='1', STRATEGY_KEY='STRING_SUBSTR' WHERE CODE='012';
UPDATE "QDATA"."ATT_CLEAN_RULE"	SET VALID_FLAG='1' WHERE CODE='021';
UPDATE "QDATA"."ATT_CLEAN_RULE"	SET VALID_FLAG='1' WHERE CODE='039';

UPDATE "QDATA"."ATT_AUDIT_RULE" SET VALID_FLAG='1' WHERE CODE in('306', '108', '111');