/*
 * Copyright © 2025-present Jiangsu Qiantong Technology Co., Ltd.
 *
 * This file is part of qData Data Middle Platform (Open Source Edition).
 *
 * qData is licensed under Apache License 2.0 with additional qData terms.
 * You may use qData for commercial purposes, but you may not remove, hide,
 * modify, or replace the qData logo, copyright notices, license notices,
 * or attribution information without a separate commercial license.
 *
 * White-label use, OEM distribution, rebranding, or presenting qData as
 * another product requires separate commercial authorization from
 * Jiangsu Qiantong Technology Co., Ltd.
 *
 * Business License: https://community.qdata.tech/business/policy.html
 * See the LICENSE file in the project root for full license information.
 */

package tech.qiantong.qdata.module.dpp.utils.ds.component;

import org.apache.commons.collections4.MapUtils;
import org.apache.commons.lang3.StringUtils;
import tech.qiantong.qdata.common.database.constants.DbQueryProperty;
import tech.qiantong.qdata.common.database.constants.DbType;
import tech.qiantong.qdata.common.database.utils.MD5Util;
import tech.qiantong.qdata.common.enums.TaskComponentTypeEnum;
import tech.qiantong.qdata.module.dpp.utils.datax.FlinkxJson;
import tech.qiantong.qdata.module.dpp.utils.model.DsResource;

import java.util.*;
import java.util.stream.Collectors;

/**
 * <P>
 * Purpose: Database input component
 * </p>
 *
 * @author: FXB
 * @create: 2025-03-12 16:31
 **/
public class DBReaderComponent implements ComponentItem {

    /**
     * taskParams SPARK (sparksql development)
     * {
     * "batchSize":1024,//Read batch size, default 1024 when empty
     * "datasource_id":1,//Source table datasource ID; null for output nodes
     * "asset_id":1,//Source table asset ID; null for output nodes
     * "table_name":1,//Source table name; auto-generated by backend for output nodes
     * "columns":["ID","NAME","AGE"],//Source table sync field list; auto-generated by backend for output nodes
     * "where":"",//Condition
     * "querySql": "sql",//When not empty, column and where cannot have values
     * }
     *
     * @param params
     * @return
     */
    @Override
    public Map<String, Object> parse(Map<String, Object> params) {
        Map<String, Object> taskParams = new LinkedHashMap<>();
        taskParams.put("localParams", params.getOrDefault("localParams", new ArrayList<>())); // Default empty list
        taskParams.put("resourceList", params.getOrDefault("resourceList", new ArrayList<>())); // Default empty list
        taskParams.put("customConfig", params.getOrDefault("customConfig", 1)); // Default fixed to 1
        taskParams.put("xms", params.getOrDefault("xms", 1)); // Default 1
        taskParams.put("xmx", params.getOrDefault("xmx", 1)); // Default 1
        taskParams.put("json", FlinkxJson.buildJobJsonMasterdata(params)); // Default empty JSON string
        return taskParams;
    }

    @Override
    public String code() {
        return TaskComponentTypeEnum.DB_READER.getCode();
    }


    /**
     * taskParams SPARK (sparksql development)
     * {
     * "batchSize":1024,//Read batch size, default 1024 when empty
     * "datasource_id":1,//Source table datasource ID; null for output nodes
     * "asset_id":1,//Source table asset ID; null for output nodes
     * "table_name":1,//Source table name; auto-generated by backend for output nodes
     * "columns":["ID","NAME","AGE"],//Source table sync field list; auto-generated by backend for output nodes
     * "where":"",//Condition
     * "querySql": "sql",//When not empty, column and where cannot have values
     * "read_type":"1",//Read mode: 1=full, 2=id increment, 3=time range increment; default full
     * "idIncrementConfig":{
     * "incrementColumn":"ID",//Increment column
     * "incrementStart":1,//Start value
     * },
     * "dateIncrementConfig":{
     * "logic":"and",//Logical operator: 1=and, 2=or; default and
     * "dateFormat":"yyyy-MM-dd",//Date format: yyyy-MM-dd or yyyy-MM-dd HH:mm:ss (manual input)
     * "column":[
     * {
     * "type":"1",//Type: 1=fixed value, 2=auto (current time), 3=SQL expression
     * "incrementColumn":"CREATE_TIME",//Increment column
     * "operator":">",//Time operator: >, >=, <, <=
     * "data":"xxx",//Fixed value: e.g. 2023-01-01; SQL expression: sql function
     * }
     * ]
     * }
     * }
     *
     * @param nodeCode
     * @param componentType
     * @param taskParams
     * @return
     */
    @Override
    public Map<String, Object> parse2(String nodeCode, Integer nodeVersion, TaskComponentTypeEnum componentType, Map<String, Object> taskParams, String resourceUrl, List<DsResource> resourceList) {
        // Reader config
        Map<String, Object> reader = new HashMap<>();
        // Input readerDatasource
        Map<String, Object> readerDatasource = (Map<String, Object>) MapUtils.getObject(taskParams, "readerDatasource");
        DbQueryProperty readerProperty = MD5Util.buildJobDatasource(readerDatasource);
        reader.put("nodeCode", nodeCode);
        reader.put("nodeVersion", nodeVersion);
        reader.put("componentType", componentType.getCode());

        // Parameters
        Map<String, Object> parameter = new HashMap<>();
        reader.put("parameter", parameter);

        parameter.put("batchSize", taskParams.getOrDefault("batchSize", 1024));
        parameter.put("datasourceId", readerDatasource.get("datasourceId"));
        parameter.put("username", readerProperty.getUsername());
        parameter.put("password", readerProperty.getPassword());
        parameter.put("dbType", readerProperty.getDbType());
        if (StringUtils.isNotBlank(readerProperty.getDbName())) {
            parameter.put("dbName", readerProperty.getDbName());
        }
        if (StringUtils.isNotBlank(readerProperty.getSid())) {
            parameter.put("sid", readerProperty.getSid());
        }
        parameter.put("column", taskParams.get("columns"));

        parameter.put("where", taskParams.get("where"));
        parameter.put("readModeType", taskParams.get("readModeType"));
        parameter.put("idIncrementConfig", taskParams.get("idIncrementConfig"));
        parameter.put("dateIncrementConfig", taskParams.get("dateIncrementConfig"));

        Map<String, Object> connection = new HashMap<>();
        if (taskParams.containsKey("querySql") && StringUtils.isNotBlank(taskParams.get("querySql").toString())) {
            connection.put("querySql", taskParams.get("querySql"));
        } else {
            connection.put("table", taskParams.get("table_name"));
        }

        connection.put("jdbcUrl", readerProperty.trainToJdbcUrl());
        parameter.put("connection", connection);
        parameter.put("readerProperty", readerProperty);
        return reader;
    }
}
