/*
 * Copyright © 2025-present Jiangsu Qiantong Technology Co., Ltd.
 *
 * This file is part of qData Data Middle Platform (Open Source Edition).
 *
 * qData is licensed under Apache License 2.0 with additional qData terms.
 * You may use qData for commercial purposes, but you may not remove, hide,
 * modify, or replace the qData logo, copyright notices, license notices,
 * or attribution information without a separate commercial license.
 *
 * White-label use, OEM distribution, rebranding, or presenting qData as
 * another product requires separate commercial authorization from
 * Jiangsu Qiantong Technology Co., Ltd.
 *
 * Business License: https://community.qdata.tech/business/policy.html
 * See the LICENSE file in the project root for full license information.
 */

package tech.qiantong.qdata.module.dpp.utils.ds.component;

import org.apache.commons.collections4.MapUtils;
import org.apache.commons.lang3.StringUtils;
import tech.qiantong.qdata.common.database.constants.DbQueryProperty;
import tech.qiantong.qdata.common.database.constants.DbType;
import tech.qiantong.qdata.common.database.utils.MD5Util;
import tech.qiantong.qdata.common.enums.TaskComponentTypeEnum;
import tech.qiantong.qdata.module.dpp.utils.datax.FlinkxJson;
import tech.qiantong.qdata.module.dpp.utils.model.DsResource;

import java.util.*;
import java.util.stream.Collectors;

/**
 * <P>
 * Purpose: Database output component
 * </p>
 *
 * @author: FXB
 * @create: 2025-03-12 16:31
 **/
public class DBWriterComponent implements ComponentItem {

    /**
     * {
     * "batchSize":1024, // Batch write size; nullable; datax defaults to 1024 when empty
     * "preSql": "", // Pre-SQL; converted to array (split by semicolon) when generating datax JSON
     * "postSql": "", // Post-SQL; converted to array (split by semicolon) when generating datax JSON
     * "target_datasource_id":1, // Target datasource ID; null if this is an input node
     * "target_asset_id":1, // Target asset ID; null if this is an input node
     * "target_table_name":1, // Target table name; auto-generated by backend if this is an input node
     * "target_columns":["ID","NAME","AGE"], // Target table sync field list; auto-generated by backend if this is an input node
     * "writeModeType": // Write mode; 1 full, 2 append, 3 incremental update
     * "selectedColumns":["ID"], // Incremental update primary key
     * }
     *
     * @param params
     * @return
     */
    @Override
    public Map<String, Object> parse(Map<String, Object> params) {
        Map<String, Object> taskParams = new LinkedHashMap<>();
        taskParams.put("localParams", params.getOrDefault("localParams", new ArrayList<>())); // Default empty list
        taskParams.put("resourceList", params.getOrDefault("resourceList", new ArrayList<>())); // Default empty list
        taskParams.put("customConfig", params.getOrDefault("customConfig", 1)); // Default fixed to 1
        taskParams.put("xms", params.getOrDefault("xms", 1)); // Default 1
        taskParams.put("xmx", params.getOrDefault("xmx", 1)); // Default 1
        taskParams.put("json", FlinkxJson.buildJobJsonMasterdata(params)); // Default empty JSON string
        return taskParams;
    }

    @Override
    public String code() {
        return TaskComponentTypeEnum.DB_READER.getCode();
    }

    @Override
    public Map<String, Object> parse2(String nodeCode, Integer nodeVersion, TaskComponentTypeEnum componentType, Map<String, Object> taskParams, String resourceUrl, List<DsResource> resourceList) {
        String preSql = MapUtils.getString(taskParams, "preSql", "");
        String postSql = MapUtils.getString(taskParams, "postSql", "");

        // Reader config
        Map<String, Object> reader = new HashMap<>();
        // Writer datasource
        Map<String, Object> writerDatasource = (Map<String, Object>) MapUtils.getObject(taskParams, "writerDatasource");
        DbQueryProperty writerProperty = MD5Util.buildJobDatasource(writerDatasource);
        reader.put("nodeCode", nodeCode);
        reader.put("nodeVersion", nodeVersion);
        reader.put("componentType", componentType.getCode());

        // Parameters
        Map<String, Object> parameter = new HashMap<>();
        reader.put("parameter", parameter);

        parameter.put("batchSize", taskParams.getOrDefault("batchSize", 1024));
        parameter.put("datasourceId", writerDatasource.get("datasourceId"));
        parameter.put("username", writerProperty.getUsername());
        parameter.put("password", writerProperty.getPassword());
        parameter.put("dbType", writerProperty.getDbType());
        if (StringUtils.isNotBlank(writerProperty.getDbName())) {
            parameter.put("dbName", writerProperty.getDbName());
        }
        if (StringUtils.isNotBlank(writerProperty.getSid())) {
            parameter.put("sid", writerProperty.getSid());
        }
        // Input fields
        parameter.put("column", taskParams.get("columns"));
        // Output fields
        parameter.put("target_column", taskParams.get("target_columns"));
        parameter.put("column", taskParams.get("columns"));
        parameter.put("selectedColumns", taskParams.getOrDefault("selectedColumns", new ArrayList<>()));
        parameter.put("writeModeType", taskParams.get("writeModeType"));
        if (StringUtils.isNotBlank(preSql)) {
            parameter.put("preSql", preSql.split(","));
        }
        if (StringUtils.isNotBlank(postSql)) {
            parameter.put("postSql", postSql.split(","));
        }
        Map<String, Object> connection = new HashMap<>();
        connection.put("table", taskParams.get("target_table_name"));
        connection.put("jdbcUrl", writerProperty.trainToJdbcUrl());
        parameter.put("connection", connection);
        parameter.put("writerProperty", writerProperty);
        return reader;
    }
}
