SET IDENTITY_INSERT "QDATA"."SYSTEM_DICT_DATA" ON;
INSERT INTO "QDATA"."SYSTEM_DICT_DATA"("DICT_CODE","DICT_SORT","DICT_LABEL","DICT_VALUE","DICT_TYPE","CSS_CLASS","LIST_CLASS","IS_DEFAULT","STATUS","CREATE_BY","CREATE_TIME","UPDATE_BY","UPDATE_TIME","REMARK") VALUES(413,5,'SQL Server2008','SQL_Server2008','datasource_type',null,'info','N','0','admin',TO_DATE('2025-11-21 19:40:47.000000000','SYYYY-MM-DD HH24:MI:SS.FF9'),'admin',TO_DATE('2025-11-21 19:41:13.000000000','SYYYY-MM-DD HH24:MI:SS.FF9'),null);
SET IDENTITY_INSERT "QDATA"."SYSTEM_JOB" OFF;

--清洗规则
UPDATE "QDATA"."ATT_CLEAN_RULE" SET VALID_FLAG='1' WHERE CODE='022';
UPDATE "QDATA"."ATT_CLEAN_RULE" SET VALID_FLAG='1' WHERE CODE='009';
UPDATE "QDATA"."ATT_CLEAN_RULE" SET VALID_FLAG='1' WHERE CODE='007';

UPDATE  "QDATA"."ATT_CLEAN_RULE"
SET STRATEGY_KEY='VALUE_REPLACE'
WHERE ID=2;
UPDATE  "QDATA"."ATT_CLEAN_RULE"
SET STRATEGY_KEY='PHONE_FORMAT_STD'
WHERE ID=6;
UPDATE  "QDATA"."ATT_CLEAN_RULE"
SET STRATEGY_KEY='DATE_FORMAT_STD'
WHERE ID=7;
UPDATE  "QDATA"."ATT_CLEAN_RULE"
SET STRATEGY_KEY='DATE_FILL_NULL'
WHERE ID=17;
UPDATE  "QDATA"."ATT_CLEAN_RULE"
SET STRATEGY_KEY='PK_DEDUP_FIRST'
WHERE ID=25;



