server:
  port: 8086
  servlet:
    context-path: /xxl-job-admin

#通用配置，开放端点
management:
  server:
    base-path: /actuator
  health:
    mail:
      enabled: false


spring:
  profiles:
    active: dev  # 默认激活的环境，可以在启动时覆盖
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  freemarker:
    templateLoaderPath: classpath:/templates/
    suffix: .ftl
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
      new_builtin_class_resolver: safer

#mybatis配置
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml

#XXL-job配置
xxl:
  job:
    accessToken: default_token
    timeout: 3
    i18n: zh_CN
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100
    logretentiondays: 30
