// AI Smart Q&A Module Language Pack
export default {
  // === ConversationList ===
  newConversation: 'New Conversation',
  searchHistory: 'Search History',
  pinTop: 'Pin',
  unpinTop: 'Unpin',
  renameTitle: 'Rename',
  titleLabel: 'Title',
  titlePlaceholder: 'Please enter a title',
  titleRequired: 'Title cannot be empty',
  renameSuccess: 'Renamed successfully',
  confirmDeleteConversation: 'Are you sure you want to delete the conversation - {title}?',
  conversationDeleted: 'Conversation deleted',
  pinned: 'Pinned',
  today: 'Today',
  oneDayAgo: '1 day ago',
  threeDaysAgo: '3 days ago',
  sevenDaysAgo: '7 days ago',
  thirtyDaysAgo: '30 days ago',

  // === DataScopeConfig ===
  newChat: 'New Chat',
  dimensionTablesCount: '+ {count} dimension tables',
  dataScope: 'Data Scope',
  configureDataScope: 'Please configure the data scope',
  dataSource: 'Data Source',
  selectDataSource: 'Please select a data source',
  factTable: 'Fact Table',
  selectFactTable: 'Please select a fact table',
  dimensionTable: 'Dimension Table',
  selectDimensionTable: 'Please select a dimension table',
  confirmScopeAndStart: 'Confirm Scope & Start',
  setAssociation: 'Set Association',
  setAssociationTitle: 'Set Association',
  selectDimensionTableName: 'Please select a dimension table',
  selectDimensionColumn: 'Please select a dimension column',
  fieldName: 'Field Name',
  chineseName: 'Display Name',
  dataType: 'Data Type',
  dimensionTableShort: 'Dim Table',
  dimensionColumn: 'Dim Column',
  cannotIdentifyAssociation: 'The association cannot be identified automatically. Would you like to set it manually?',
  cannotConfirmSession: 'Unable to determine the current session ID. Please save the configuration and start Q&A first.',
  selectDimensionColumnForField: 'Field [{name}] has a dimension table selected. Please select the corresponding dimension column',
  setAtLeastOneAssociation: 'Please set at least one association',
  setAssociationSuccess: 'Association set successfully',

  // === Message ===
  insight: 'Smart Insight',
  analyzing: 'Analyzing...',
  suggestedAsk: 'Try asking',
  relationshipNotIdentified: 'Association cannot be identified automatically',
  dialogError: 'Conversation Error',
  analyzingData: 'Analyzing data and generating reports, please wait...',
  thinking: 'Thinking...',
  visualization: 'Visualization',
  detailData: 'Detail Data',
  data: 'Data',
  dataLabel: 'Data {n}',
  downloadChart: 'Download Chart',
  copySuccess: 'Copied successfully!',
  exportSuccess: 'Exported successfully!',
  exportFailed: 'Export failed, please try again!',
  exporting: 'Exporting, please wait...',
  chartFile: 'Chart_{time}',
  detailFile: 'DetailData_{time}',
  confirmDeleteMessage: 'Are you sure you want to delete?',

  // === MessageListEmpty ===
  welcomeGreeting: 'Hello, I am qData Smart Q&A. Nice to meet you!',
  welcomeSubheading: 'Simplify complexity, make data analysis more efficient.',
  inputPlaceholder: 'Ask qData Smart Q&A... (Shift+Enter for new line, Enter to send)',
  selectModel: 'Select Model',
  answerType: 'Answer Type',
  disclaimer: 'This content is generated by qData Smart Q&A and may not be entirely accurate.',
  configureDataScopeFirst: 'Please configure the data scope first!',

  // === MessageListEmpty2 ===
  lingtongAI: 'Lingtong AI',

  // === MessageNewConversation ===
  startConversation: 'Click the button below to start your conversation',

  // === Chat Index ===
  clearSession: 'Clear Session',
  navDown: 'Down',
  navUp: 'Up',
  send: 'Send',
  stop: 'Stop',
  cannotSwitchDuringConversation: 'Cannot switch during a conversation!',
  cannotDeleteDuringAnswer: 'Cannot delete while answering!',
  confirmClearMessages: 'Are you sure you want to clear all messages?',
  sendFailedEmpty: 'Send failed: content is empty!',
  selectAnswerType: 'Please select an answer type (Smart Q&A or Smart Chart) first!',

  // === AssistantReportCard ===
  quantity: 'Quantity',

  // === MessageListEmpty2 prompt ===
  promptWeather: "How's the weather today?",
  promptPoem: 'Write a beautiful poem?',

  // === constants.js ===
  smartChart: 'Smart Chart',
  smartQA: 'Smart Q&A'
}

