# Copyright © 2025-present Jiangsu Qiantong Technology Co., Ltd.
#
# This file is part of qData Data Middle Platform (Open Source Edition).
#
# qData is licensed under Apache License 2.0 with additional qData terms.
# You may use qData for commercial purposes, but you may not remove, hide,
# modify, or replace the qData logo, copyright notices, license notices,
# or attribution information without a separate commercial license.
#
# White-label use, OEM distribution, rebranding, or presenting qData as
# another product requires separate commercial authorization from
# Jiangsu Qiantong Technology Co., Ltd.
#
# Business License: https://community.qdata.tech/business/policy.html
# See the LICENSE file in the project root for full license information.

version: "3.8"

services:
  # qData backend service
  qdata-api:
    image: ${QDATA_HUB}/qdata-server-ce:${QDATA_TAG}
    restart: always
    profiles: [ "all", "light" ]
    env_file: .env
    environment:
      - TZ=Asia/Shanghai
#    ports:
#      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./qdata-server/logs:/usr/app/jar/logs
      - ./qdata-server/upload:/usr/app/jar/upload
      - ./qdata-server/application-prod.yml:/usr/app/jar/application-prod.yml
      - ./qdata-server/datax:/usr/app/jar/datax
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      dm8:
        condition: service_healthy
    networks:
      - qdatanet

  # qData quality service
  qdata-service-quality:
    image: ${QDATA_HUB}/qdata-service-quality-ce:${QDATA_TAG}
    restart: always
    profiles: [ "all", "light" ]
    env_file: .env
    environment:
      - TZ=Asia/Shanghai
#    ports:
#      - "8083:8083"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./qdata-service-quality/logs:/usr/app/jar/logs
      - ./qdata-service-quality/job-log:/usr/app/jar/job-log
      - ./qdata-service-quality/application-prod.yml:/usr/app/jar/application-prod.yml
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      dm8:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    networks:
      - qdatanet

  # qData AI service
  qdata-service-ai:
    privileged: true
    image: ${QDATA_HUB}/qdata-service-ai-ce:${QDATA_TAG}
    restart: always
    profiles: [ "all", "light" ]
    env_file: .env
    environment:
      - TZ=Asia/Shanghai
    #    ports:
    #      - "8087:8087"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./qdata-service-ai/logs:/usr/app/jar/logs
      - ./qdata-service-ai/application-prod.yml:/usr/app/jar/application-prod.yml
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      dm8:
        condition: service_healthy
    networks:
      - qdatanet
    extra_hosts:
      - "host.docker.internal:host-gateway"
