# Copyright © 2025-present Jiangsu Qiantong Technology Co., Ltd.
#
# This file is part of qData Data Middle Platform (Open Source Edition).
#
# qData is licensed under Apache License 2.0 with additional qData terms.
# You may use qData for commercial purposes, but you may not remove, hide,
# modify, or replace the qData logo, copyright notices, license notices,
# or attribution information without a separate commercial license.
#
# White-label use, OEM distribution, rebranding, or presenting qData as
# another product requires separate commercial authorization from
# Jiangsu Qiantong Technology Co., Ltd.
#
# Business License: https://community.qdata.tech/business/policy.html
# See the LICENSE file in the project root for full license information.

payment:
  alipay:
    # 应用ID
    appId: xxxxx
    # 应用私钥
    appPrivateKey: xxxxx
    # 支付宝公钥
    alipayPublicKey: xxxxx
    # 回调接口
    notifyUrl: xxxxx
    # 重定向回来路径
    returnUrl: xxxxx
    # 沙箱环境支付网地址 正式环境：openapi.alipay.com
    gatewayHost: xxxxx
    # 沙箱环境支付网地址 正式环境：https://openapi.alipay.com/gateway.do
    gatewayUrl: xxxxx
  wechat:
    # 应用ID
    appId: XXXXXX
    # 应用私钥
    appPrivateKey: XXXXXX
    # 支付宝公钥
    alipayPublicKey: XXXXXX
    # 回调接口
    notifyUrl:  http://bxbunc.natappfree.cc/alipay/notify
