CREATE TABLE "MC_COLUMN"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "TASK_ID" BIGINT,
    "DB_ID" BIGINT,
    "TABLE_ID" BIGINT,
    "DATASOURCE_ID" BIGINT,
    "VERSION" INTEGER DEFAULT 1 NOT NULL,
    "SAFETY_LEVEL_ID" BIGINT,
    "DATA_ELEM_ID" BIGINT,
    "COLUMN_NAME" VARCHAR2(256),
    "COLUMN_COMMENT" VARCHAR2(2000),
    "COLUMN_TYPE" VARCHAR2(128),
    "COLUMN_LENGTH" INTEGER,
    "COLUMN_PRECISION" INTEGER,
    "COLUMN_SCALE" INTEGER,
    "DEFAULT_VALUE" VARCHAR2(128),
    "PK_FLAG" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "FK_FLAG" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "NULLABLE_FLAG" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "BUSINESS_DEFINITION" VARCHAR2(128),
    "MEASURING_UNIT" VARCHAR2(32),
    "DATA_QUALITY" INTEGER DEFAULT 100 NOT NULL,
    "AUDIT_STATUS" VARCHAR2(10) DEFAULT '2',
    "AUDIT_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP,
    "STATUS" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "VALID_FLAG" VARCHAR2(1) DEFAULT '1' NOT NULL,
    "DEL_FLAG" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "CREATE_BY" VARCHAR2(32),
    "CREATOR_ID" BIGINT,
    "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_BY" VARCHAR2(32),
    "UPDATER_ID" BIGINT,
    "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "REMARK" VARCHAR2(512),
    "DESCRIPTION" VARCHAR2(512),
    "PORTAL_VISIBLE" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "AUTO_INCREMENT_FLAG" CHAR(1) DEFAULT '0',
    "PARTITION_FLAG" CHAR(1) DEFAULT '0',
    "COLUMN_STANDARD" VARCHAR2(128),
    "VALUE_RULE" VARCHAR2(128),
    "RESPONSIBLE_DEPT" BIGINT,
    "BUSINESS_LEADER" BIGINT,
    "UNIQUE_FLAG" CHAR(1),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "MC_COLUMN" IS '元数据字段信息表';
COMMENT ON COLUMN "MC_COLUMN"."AUDIT_STATUS" IS '审核状态;1：审批中，2：审批通过，3：审批拒绝，4：审批撤回，5：审批异常';
COMMENT ON COLUMN "MC_COLUMN"."AUDIT_TIME" IS '审核时间';
COMMENT ON COLUMN "MC_COLUMN"."AUTO_INCREMENT_FLAG" IS '是否自增 (0:否, 1:是)';
COMMENT ON COLUMN "MC_COLUMN"."BUSINESS_DEFINITION" IS '业务定义';
COMMENT ON COLUMN "MC_COLUMN"."BUSINESS_LEADER" IS '负责人';
COMMENT ON COLUMN "MC_COLUMN"."COLUMN_COMMENT" IS '字段注释';
COMMENT ON COLUMN "MC_COLUMN"."COLUMN_LENGTH" IS '数据长度';
COMMENT ON COLUMN "MC_COLUMN"."COLUMN_NAME" IS '字段名称';
COMMENT ON COLUMN "MC_COLUMN"."COLUMN_PRECISION" IS '数据精度';
COMMENT ON COLUMN "MC_COLUMN"."COLUMN_SCALE" IS '数据小数位';
COMMENT ON COLUMN "MC_COLUMN"."COLUMN_STANDARD" IS '字段规范';
COMMENT ON COLUMN "MC_COLUMN"."COLUMN_TYPE" IS '字段类型';
COMMENT ON COLUMN "MC_COLUMN"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "MC_COLUMN"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "MC_COLUMN"."CREATOR_ID" IS '创建人id';
COMMENT ON COLUMN "MC_COLUMN"."DATA_ELEM_ID" IS '数据元id';
COMMENT ON COLUMN "MC_COLUMN"."DATA_QUALITY" IS '数据质量';
COMMENT ON COLUMN "MC_COLUMN"."DATASOURCE_ID" IS '数据源id;冗余字段';
COMMENT ON COLUMN "MC_COLUMN"."DB_ID" IS '库id';
COMMENT ON COLUMN "MC_COLUMN"."DEFAULT_VALUE" IS '数据默认值';
COMMENT ON COLUMN "MC_COLUMN"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';
COMMENT ON COLUMN "MC_COLUMN"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "MC_COLUMN"."FK_FLAG" IS '是否外键;0:否 1:是';
COMMENT ON COLUMN "MC_COLUMN"."ID" IS 'ID';
COMMENT ON COLUMN "MC_COLUMN"."MEASURING_UNIT" IS '度量单位';
COMMENT ON COLUMN "MC_COLUMN"."NULLABLE_FLAG" IS '是否可空;0:否 1:是';
COMMENT ON COLUMN "MC_COLUMN"."PARTITION_FLAG" IS '是否分区字段 (0:否, 1:是)';
COMMENT ON COLUMN "MC_COLUMN"."PK_FLAG" IS '是否主键;0:否 1:是';
COMMENT ON COLUMN "MC_COLUMN"."PORTAL_VISIBLE" IS '是否在门户展示：0-不展示，1-展示';
COMMENT ON COLUMN "MC_COLUMN"."REMARK" IS '备注';
COMMENT ON COLUMN "MC_COLUMN"."RESPONSIBLE_DEPT" IS '责任部门';
COMMENT ON COLUMN "MC_COLUMN"."SAFETY_LEVEL_ID" IS '安全等级id';
COMMENT ON COLUMN "MC_COLUMN"."STATUS" IS '状态;0：未发布，1：已发布';
COMMENT ON COLUMN "MC_COLUMN"."TABLE_ID" IS '表信息id';
COMMENT ON COLUMN "MC_COLUMN"."TASK_ID" IS '采集任务id;预留字段，暂时不用';
COMMENT ON COLUMN "MC_COLUMN"."UNIQUE_FLAG" IS '是否唯一';
COMMENT ON COLUMN "MC_COLUMN"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "MC_COLUMN"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "MC_COLUMN"."UPDATER_ID" IS '更新人id';
COMMENT ON COLUMN "MC_COLUMN"."VALID_FLAG" IS '是否有效;0：无效，1：有效';
COMMENT ON COLUMN "MC_COLUMN"."VALUE_RULE" IS '取值逻辑';
COMMENT ON COLUMN "MC_COLUMN"."VERSION" IS '版本';


CREATE TABLE "MC_COLUMN_LOG"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "DATA_TYPE" VARCHAR2(10) DEFAULT '1' NOT NULL,
    "TASK_ID" BIGINT,
    "COLUMN_ID" BIGINT NOT NULL,
    "VERSION" INTEGER DEFAULT 1 NOT NULL,
    "DB_ID" BIGINT NOT NULL,
    "TABLE_ID" BIGINT NOT NULL,
    "DATASOURCE_ID" BIGINT NOT NULL,
    "SAFETY_LEVEL_ID" BIGINT,
    "DATA_ELEM_ID" BIGINT,
    "COLUMN_NAME" VARCHAR2(256) NOT NULL,
    "COLUMN_COMMENT" VARCHAR2(2000),
    "COLUMN_TYPE" VARCHAR2(128) NOT NULL,
    "COLUMN_LENGTH" INTEGER,
    "COLUMN_PRECISION" INTEGER,
    "COLUMN_SCALE" INTEGER,
    "DEFAULT_VALUE" VARCHAR2(128),
    "PK_FLAG" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "FK_FLAG" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "NULLABLE_FLAG" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "BUS_DEFINITION" VARCHAR2(128),
    "MEASURING_UNIT" VARCHAR2(32),
    "DATA_QUALITY" INTEGER DEFAULT 100 NOT NULL,
    "UPDATE_TYPE" VARCHAR2(10),
    "UPDATE_MSG" VARCHAR2(512),
    "VALID_FLAG" VARCHAR2(1) DEFAULT '1' NOT NULL,
    "DEL_FLAG" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "CREATE_BY" VARCHAR2(32),
    "CREATOR_ID" BIGINT,
    "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_BY" VARCHAR2(32),
    "UPDATER_ID" BIGINT,
    "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "REMARK" VARCHAR2(512),
    "DESCRIPTION" VARCHAR2(512),
    "CHANGE_TYPE" VARCHAR2(1) DEFAULT '0',
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "MC_COLUMN_LOG" IS '元数据字段信息 - 日志表';
COMMENT ON COLUMN "MC_COLUMN_LOG"."BUS_DEFINITION" IS '业务定义';
COMMENT ON COLUMN "MC_COLUMN_LOG"."CHANGE_TYPE" IS '变更类型：0-无变化，1-新增，2-修改，3-删除';
COMMENT ON COLUMN "MC_COLUMN_LOG"."COLUMN_COMMENT" IS '字段注释';
COMMENT ON COLUMN "MC_COLUMN_LOG"."COLUMN_ID" IS '字段 id';
COMMENT ON COLUMN "MC_COLUMN_LOG"."COLUMN_LENGTH" IS '数据长度';
COMMENT ON COLUMN "MC_COLUMN_LOG"."COLUMN_NAME" IS '字段名称';
COMMENT ON COLUMN "MC_COLUMN_LOG"."COLUMN_PRECISION" IS '数据精度';
COMMENT ON COLUMN "MC_COLUMN_LOG"."COLUMN_SCALE" IS '数据小数位';
COMMENT ON COLUMN "MC_COLUMN_LOG"."COLUMN_TYPE" IS '字段类型';
COMMENT ON COLUMN "MC_COLUMN_LOG"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "MC_COLUMN_LOG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "MC_COLUMN_LOG"."CREATOR_ID" IS '创建人 id';
COMMENT ON COLUMN "MC_COLUMN_LOG"."DATA_ELEM_ID" IS '数据元 id';
COMMENT ON COLUMN "MC_COLUMN_LOG"."DATA_QUALITY" IS '数据质量';
COMMENT ON COLUMN "MC_COLUMN_LOG"."DATA_TYPE" IS '数据类型;数据类型 1：预发布 2：采集，预留字段，暂时不用';
COMMENT ON COLUMN "MC_COLUMN_LOG"."DATASOURCE_ID" IS '数据源 id;冗余字段';
COMMENT ON COLUMN "MC_COLUMN_LOG"."DB_ID" IS '库 id';
COMMENT ON COLUMN "MC_COLUMN_LOG"."DEFAULT_VALUE" IS '数据默认值';
COMMENT ON COLUMN "MC_COLUMN_LOG"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';
COMMENT ON COLUMN "MC_COLUMN_LOG"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "MC_COLUMN_LOG"."FK_FLAG" IS '是否外键;0:否 1:是';
COMMENT ON COLUMN "MC_COLUMN_LOG"."ID" IS 'ID';
COMMENT ON COLUMN "MC_COLUMN_LOG"."MEASURING_UNIT" IS '度量单位';
COMMENT ON COLUMN "MC_COLUMN_LOG"."NULLABLE_FLAG" IS '是否可空;0:否 1:是';
COMMENT ON COLUMN "MC_COLUMN_LOG"."PK_FLAG" IS '是否主键;0:否 1:是';
COMMENT ON COLUMN "MC_COLUMN_LOG"."REMARK" IS '备注';
COMMENT ON COLUMN "MC_COLUMN_LOG"."SAFETY_LEVEL_ID" IS '安全等级 id';
COMMENT ON COLUMN "MC_COLUMN_LOG"."TABLE_ID" IS '表信息 id';
COMMENT ON COLUMN "MC_COLUMN_LOG"."TASK_ID" IS '采集任务 id;预留字段，暂时不用';
COMMENT ON COLUMN "MC_COLUMN_LOG"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "MC_COLUMN_LOG"."UPDATE_MSG" IS '变更说明';
COMMENT ON COLUMN "MC_COLUMN_LOG"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "MC_COLUMN_LOG"."UPDATE_TYPE" IS '变更类型';
COMMENT ON COLUMN "MC_COLUMN_LOG"."UPDATER_ID" IS '更新人 id';
COMMENT ON COLUMN "MC_COLUMN_LOG"."VALID_FLAG" IS '是否有效;0：无效，1：有效';
COMMENT ON COLUMN "MC_COLUMN_LOG"."VERSION" IS '版本';

CREATE TABLE "MC_DB"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "TASK_ID" BIGINT,
    "SOURCE_SYSTEM_ID" BIGINT,
    "SOURCE_SYSTEM_NAME" VARCHAR2(128),
    "VERSION" INTEGER DEFAULT 1 NOT NULL,
    "DATASOURCE_ID" BIGINT NOT NULL,
    "IP" VARCHAR2(32) NOT NULL,
    "PORT" INTEGER NOT NULL,
    "DATASOURCE_CONFIG" VARCHAR2(1024),
    "DB_TYPE" VARCHAR2(32) NOT NULL,
    "DB_NAME" VARCHAR2(128) NOT NULL,
    "SCHEMA_NAME" VARCHAR2(128),
    "SAFETY_LEVEL_ID" BIGINT,
    "BELONGING_LAYER" VARCHAR2(10),
    "BELONGING_SYSTEM" VARCHAR2(128),
    "BUSINESS_LEADER" BIGINT,
    "BUSINESS_LEADER_PHONE" VARCHAR2(32),
    "TECH_LEADER" BIGINT,
    "TECH_LEADER_PHONE" VARCHAR2(32),
    "STORAGE_SIZE" BIGINT DEFAULT 0,
    "DATA_QUALITY" INTEGER DEFAULT 100 NOT NULL,
    "AUDIT_STATUS" VARCHAR2(10) DEFAULT '2',
    "AUDIT_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP,
    "STATUS" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "VALID_FLAG" VARCHAR2(1) DEFAULT '1' NOT NULL,
    "DEL_FLAG" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "CREATE_BY" VARCHAR2(32),
    "CREATOR_ID" BIGINT,
    "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_BY" VARCHAR2(32),
    "UPDATER_ID" BIGINT,
    "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "REMARK" VARCHAR2(512),
    "DESCRIPTION" VARCHAR2(512),
    "PORTAL_VISIBLE" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "STORAGE_ENGINE" VARCHAR2(128),
    "RESPONSIBLE_DEPT" BIGINT,
    "DATA_ROW_COUNT" INTEGER,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "MC_DB" IS '数据库表';
COMMENT ON COLUMN "MC_DB"."AUDIT_STATUS" IS '审核状态;1：审批中，2：审批通过，3：审批拒绝，4：审批撤回，5：审批异常';
COMMENT ON COLUMN "MC_DB"."AUDIT_TIME" IS '审核时间';
COMMENT ON COLUMN "MC_DB"."BELONGING_LAYER" IS '所属分层;1:ODS 2:DWD 3:DWS  4:ADS 5:外部系统）';
COMMENT ON COLUMN "MC_DB"."BELONGING_SYSTEM" IS '所属系统';
COMMENT ON COLUMN "MC_DB"."BUSINESS_LEADER" IS '业务责任人';
COMMENT ON COLUMN "MC_DB"."BUSINESS_LEADER_PHONE" IS '业务责任人电话';
COMMENT ON COLUMN "MC_DB"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "MC_DB"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "MC_DB"."CREATOR_ID" IS '创建人id';
COMMENT ON COLUMN "MC_DB"."DATA_QUALITY" IS '数据质量';
COMMENT ON COLUMN "MC_DB"."DATA_ROW_COUNT" IS '数据行数';
COMMENT ON COLUMN "MC_DB"."DATASOURCE_CONFIG" IS '数据源配置(json字符串)';
COMMENT ON COLUMN "MC_DB"."DATASOURCE_ID" IS '数据源id';
COMMENT ON COLUMN "MC_DB"."DB_NAME" IS '数据库名称';
COMMENT ON COLUMN "MC_DB"."DB_TYPE" IS '数据库类型';
COMMENT ON COLUMN "MC_DB"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';
COMMENT ON COLUMN "MC_DB"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "MC_DB"."SOURCE_SYSTEM_NAME" IS '来源系统名称';
COMMENT ON COLUMN "MC_DB"."SOURCE_SYSTEM_ID" IS '来源系统id';
COMMENT ON COLUMN "MC_DB"."ID" IS 'ID';
COMMENT ON COLUMN "MC_DB"."IP" IS 'IP';
COMMENT ON COLUMN "MC_DB"."PORT" IS '端口号';
COMMENT ON COLUMN "MC_DB"."REMARK" IS '备注';
COMMENT ON COLUMN "MC_DB"."RESPONSIBLE_DEPT" IS '责任部门';
COMMENT ON COLUMN "MC_DB"."SAFETY_LEVEL_ID" IS '安全等级id';
COMMENT ON COLUMN "MC_DB"."SCHEMA_NAME" IS '模式名;可空';
COMMENT ON COLUMN "MC_DB"."STATUS" IS '状态;0：未发布，1：已发布';
COMMENT ON COLUMN "MC_DB"."STORAGE_ENGINE" IS '存储引擎';
COMMENT ON COLUMN "MC_DB"."STORAGE_SIZE" IS '存储大小';
COMMENT ON COLUMN "MC_DB"."TASK_ID" IS '采集任务id;预留字段，暂时不用';
COMMENT ON COLUMN "MC_DB"."TECH_LEADER" IS '技术责任人';
COMMENT ON COLUMN "MC_DB"."TECH_LEADER_PHONE" IS '技术责任人电话';
COMMENT ON COLUMN "MC_DB"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "MC_DB"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "MC_DB"."UPDATER_ID" IS '更新人id';
COMMENT ON COLUMN "MC_DB"."VALID_FLAG" IS '是否有效;0：无效，1：有效';
COMMENT ON COLUMN "MC_DB"."VERSION" IS '版本';


CREATE TABLE "MC_DOMAIN"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "NAME" VARCHAR2(128) NOT NULL,
    "PARENT_ID" BIGINT,
    "SORT_ORDER" INTEGER NOT NULL,
    "CODE" VARCHAR2(128) NOT NULL,
    "VALID_FLAG" VARCHAR2(1) DEFAULT '1' NOT NULL,
    "DEL_FLAG" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "CREATE_BY" VARCHAR2(32),
    "CREATOR_ID" BIGINT,
    "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_BY" VARCHAR2(32),
    "UPDATER_ID" BIGINT,
    "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "REMARK" VARCHAR2(512),
    "DESCRIPTION" VARCHAR2(512),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "MC_DOMAIN" IS '业务域表';
COMMENT ON COLUMN "MC_DOMAIN"."CODE" IS '层级编码';
COMMENT ON COLUMN "MC_DOMAIN"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "MC_DOMAIN"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "MC_DOMAIN"."CREATOR_ID" IS '创建人id';
COMMENT ON COLUMN "MC_DOMAIN"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';
COMMENT ON COLUMN "MC_DOMAIN"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "MC_DOMAIN"."ID" IS 'ID';
COMMENT ON COLUMN "MC_DOMAIN"."NAME" IS '业务名称';
COMMENT ON COLUMN "MC_DOMAIN"."PARENT_ID" IS '关联上级ID';
COMMENT ON COLUMN "MC_DOMAIN"."REMARK" IS '备注';
COMMENT ON COLUMN "MC_DOMAIN"."SORT_ORDER" IS '类别排序';
COMMENT ON COLUMN "MC_DOMAIN"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "MC_DOMAIN"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "MC_DOMAIN"."UPDATER_ID" IS '更新人id';
COMMENT ON COLUMN "MC_DOMAIN"."VALID_FLAG" IS '是否有效;0：无效，1：有效';


CREATE TABLE "MC_TABLE"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "TASK_ID" BIGINT,
    "DB_ID" BIGINT,
    "DATASOURCE_ID" BIGINT,
    "VERSION" INTEGER DEFAULT 1 NOT NULL,
    "TABLE_NAME" VARCHAR2(256),
    "TABLE_COMMENT" VARCHAR2(2000),
    "SAFETY_LEVEL_ID" BIGINT,
    "DB_NAME" VARCHAR2(64),
    "SCHEMA_NAME" VARCHAR2(64),
    "STORAGE_TYPE" VARCHAR2(32),
    "STORAGE_SIZE" BIGINT,
    "BUSINESS_LEADER" BIGINT,
    "BUSINESS_LEADER_PHONE" VARCHAR2(32),
    "TECH_LEADER" BIGINT,
    "TECH_LEADER_PHONE" VARCHAR2(32),
    "MASTER_FLAG" VARCHAR2(1),
    "TEMP_FLAG" VARCHAR2(1),
    "DATA_QUALITY" INTEGER DEFAULT 100 NOT NULL,
    "AUDIT_STATUS" VARCHAR2(10) DEFAULT '2',
    "AUDIT_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP,
    "STATUS" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "VALID_FLAG" VARCHAR2(1) DEFAULT '1' NOT NULL,
    "DEL_FLAG" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "CREATE_BY" VARCHAR2(32),
    "CREATOR_ID" BIGINT,
    "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_BY" VARCHAR2(32),
    "UPDATER_ID" BIGINT,
    "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "REMARK" VARCHAR2(512),
    "DESCRIPTION" VARCHAR2(512),
    "PORTAL_VISIBLE" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "COLUMN_COUNT" INTEGER,
    "TB_INDEX" VARCHAR2(1024),
    "ROW_COUNT" INTEGER,
    "PARTITION_KEY" VARCHAR2(128),
    "STORAGE_ENGINE" VARCHAR(128),
    "RESPONSIBLE_DEPT" BIGINT,
    "PRIMARY_KEY" VARCHAR(128),
    "TB_CREATE_TIME" DATETIME(6),
    "DATA_UPDATE_TIME" DATETIME(6),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "MC_TABLE" IS '元数据表信息表';
COMMENT ON COLUMN "MC_TABLE"."AUDIT_STATUS" IS '审核状态;1：审批中，2：审批通过，3：审批拒绝，4：审批撤回，5：审批异常';
COMMENT ON COLUMN "MC_TABLE"."AUDIT_TIME" IS '审核时间';
COMMENT ON COLUMN "MC_TABLE"."BUSINESS_LEADER" IS '业务责任人';
COMMENT ON COLUMN "MC_TABLE"."BUSINESS_LEADER_PHONE" IS '业务责任人电话';
COMMENT ON COLUMN "MC_TABLE"."COLUMN_COUNT" IS '字段数量';
COMMENT ON COLUMN "MC_TABLE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "MC_TABLE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "MC_TABLE"."CREATOR_ID" IS '创建人id';
COMMENT ON COLUMN "MC_TABLE"."DATA_QUALITY" IS '数据质量';
COMMENT ON COLUMN "MC_TABLE"."DATA_UPDATE_TIME" IS '数据更新时间';
COMMENT ON COLUMN "MC_TABLE"."DATASOURCE_ID" IS '数据源id;冗余字段';
COMMENT ON COLUMN "MC_TABLE"."DB_ID" IS '库id';
COMMENT ON COLUMN "MC_TABLE"."DB_NAME" IS '数据库名';
COMMENT ON COLUMN "MC_TABLE"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';
COMMENT ON COLUMN "MC_TABLE"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "MC_TABLE"."ID" IS 'ID';
COMMENT ON COLUMN "MC_TABLE"."MASTER_FLAG" IS '是否主表;0：否，1：是';
COMMENT ON COLUMN "MC_TABLE"."PARTITION_KEY" IS '分区字段';
COMMENT ON COLUMN "MC_TABLE"."PORTAL_VISIBLE" IS '是否在门户展示：0-不展示，1-展示';
COMMENT ON COLUMN "MC_TABLE"."PRIMARY_KEY" IS '主键字段';
COMMENT ON COLUMN "MC_TABLE"."REMARK" IS '备注';
COMMENT ON COLUMN "MC_TABLE"."RESPONSIBLE_DEPT" IS '责任部门';
COMMENT ON COLUMN "MC_TABLE"."ROW_COUNT" IS '行数';
COMMENT ON COLUMN "MC_TABLE"."SAFETY_LEVEL_ID" IS '安全等级id';
COMMENT ON COLUMN "MC_TABLE"."SCHEMA_NAME" IS '模式名;可空';
COMMENT ON COLUMN "MC_TABLE"."STATUS" IS '状态;0：未发布，1：已发布';
COMMENT ON COLUMN "MC_TABLE"."STORAGE_ENGINE" IS '存储引擎';
COMMENT ON COLUMN "MC_TABLE"."STORAGE_SIZE" IS '存储大小';
COMMENT ON COLUMN "MC_TABLE"."STORAGE_TYPE" IS '存储类型';
COMMENT ON COLUMN "MC_TABLE"."TABLE_COMMENT" IS '表注释/表描述（表中文名称）';
COMMENT ON COLUMN "MC_TABLE"."TABLE_NAME" IS '表名称（表英文名称）';
COMMENT ON COLUMN "MC_TABLE"."TASK_ID" IS '采集任务id;预留字段，暂时不用';
COMMENT ON COLUMN "MC_TABLE"."TB_CREATE_TIME" IS '表创建时间';
COMMENT ON COLUMN "MC_TABLE"."TB_INDEX" IS '索引';
COMMENT ON COLUMN "MC_TABLE"."TECH_LEADER" IS '技术责任人';
COMMENT ON COLUMN "MC_TABLE"."TECH_LEADER_PHONE" IS '技术责任人电话';
COMMENT ON COLUMN "MC_TABLE"."TEMP_FLAG" IS '是否临时表;0：否，1：是';
COMMENT ON COLUMN "MC_TABLE"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "MC_TABLE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "MC_TABLE"."UPDATER_ID" IS '更新人id';
COMMENT ON COLUMN "MC_TABLE"."VALID_FLAG" IS '是否有效;0：无效，1：有效';
COMMENT ON COLUMN "MC_TABLE"."VERSION" IS '版本';


CREATE TABLE "MC_TABLE_COLUMN_REL_LOG"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "DATA_TYPE" VARCHAR2(10) DEFAULT '1' NOT NULL,
    "TASK_ID" BIGINT,
    "DB_ID" BIGINT NOT NULL,
    "DB_VERSION" INTEGER NOT NULL,
    "TABLE_ID" BIGINT NOT NULL,
    "TABLE_VERSION" INTEGER NOT NULL,
    "COLUMN_ID" BIGINT NOT NULL,
    "COLUMN_VERSION" INTEGER NOT NULL,
    "VALID_FLAG" VARCHAR2(1) DEFAULT '1' NOT NULL,
    "DEL_FLAG" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "CREATE_BY" VARCHAR2(32),
    "CREATOR_ID" BIGINT,
    "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_BY" VARCHAR2(32),
    "UPDATER_ID" BIGINT,
    "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "REMARK" VARCHAR2(512),
    "DESCRIPTION" VARCHAR2(512),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "MC_TABLE_COLUMN_REL_LOG" IS '元数据数据库与表信息及字段信息关系-日志表';
COMMENT ON COLUMN "MC_TABLE_COLUMN_REL_LOG"."COLUMN_ID" IS '字段 id';
COMMENT ON COLUMN "MC_TABLE_COLUMN_REL_LOG"."COLUMN_VERSION" IS '字段版本';
COMMENT ON COLUMN "MC_TABLE_COLUMN_REL_LOG"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "MC_TABLE_COLUMN_REL_LOG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "MC_TABLE_COLUMN_REL_LOG"."CREATOR_ID" IS '创建人 id';
COMMENT ON COLUMN "MC_TABLE_COLUMN_REL_LOG"."DATA_TYPE" IS '数据类型;数据类型 1：预发布 2：采集，预留字段，暂时不用';
COMMENT ON COLUMN "MC_TABLE_COLUMN_REL_LOG"."DB_ID" IS '库 id';
COMMENT ON COLUMN "MC_TABLE_COLUMN_REL_LOG"."DB_VERSION" IS '库版本';
COMMENT ON COLUMN "MC_TABLE_COLUMN_REL_LOG"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';
COMMENT ON COLUMN "MC_TABLE_COLUMN_REL_LOG"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "MC_TABLE_COLUMN_REL_LOG"."ID" IS 'ID';
COMMENT ON COLUMN "MC_TABLE_COLUMN_REL_LOG"."REMARK" IS '备注';
COMMENT ON COLUMN "MC_TABLE_COLUMN_REL_LOG"."TABLE_ID" IS '表 id';
COMMENT ON COLUMN "MC_TABLE_COLUMN_REL_LOG"."TABLE_VERSION" IS '表版本';
COMMENT ON COLUMN "MC_TABLE_COLUMN_REL_LOG"."TASK_ID" IS '采集任务 id;预留字段，暂时不用';
COMMENT ON COLUMN "MC_TABLE_COLUMN_REL_LOG"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "MC_TABLE_COLUMN_REL_LOG"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "MC_TABLE_COLUMN_REL_LOG"."UPDATER_ID" IS '更新人 id';
COMMENT ON COLUMN "MC_TABLE_COLUMN_REL_LOG"."VALID_FLAG" IS '是否有效;0：无效，1：有效';


CREATE TABLE "MC_TABLE_LOG"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "DATA_TYPE" VARCHAR2(10) DEFAULT '1' NOT NULL,
    "TASK_ID" BIGINT,
    "TABLE_ID" BIGINT NOT NULL,
    "VERSION" VARCHAR2(50) DEFAULT 1 NOT NULL,
    "DB_ID" BIGINT NOT NULL,
    "DATASOURCE_ID" BIGINT NOT NULL,
    "TABLE_NAME" VARCHAR2(256) NOT NULL,
    "TABLE_COMMENT" VARCHAR2(2000),
    "SAFETY_LEVEL_ID" BIGINT,
    "DB_NAME" VARCHAR2(128) NOT NULL,
    "SCHEMA_NAME" VARCHAR2(128),
    "STORAGE_TYPE" VARCHAR2(32),
    "STORAGE_SIZE" INTEGER,
    "BUSINESS_LEADER" BIGINT,
    "BUSINESS_LEADER_PHONE" VARCHAR2(32),
    "TECH_LEADER" BIGINT,
    "TECH_LEADER_PHONE" VARCHAR2(32),
    "MASTER_FLAG" VARCHAR2(1),
    "TEMP_FLAG" VARCHAR2(1),
    "DATA_QUALITY" INTEGER DEFAULT 100 NOT NULL,
    "UPDATE_TYPE" VARCHAR2(10),
    "UPDATE_MSG" VARCHAR2(512),
    "VALID_FLAG" VARCHAR2(1) DEFAULT '1' NOT NULL,
    "DEL_FLAG" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "CREATE_BY" VARCHAR2(32),
    "CREATOR_ID" BIGINT,
    "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_BY" VARCHAR2(32),
    "UPDATER_ID" BIGINT,
    "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "REMARK" VARCHAR2(512),
    "DESCRIPTION" VARCHAR2(512),
    "INSTANCE_ID" BIGINT,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "MC_TABLE_LOG" IS '元数据表信息 - 日志表';
COMMENT ON COLUMN "MC_TABLE_LOG"."BUSINESS_LEADER" IS '业务责任人';
COMMENT ON COLUMN "MC_TABLE_LOG"."BUSINESS_LEADER_PHONE" IS '业务责任人电话';
COMMENT ON COLUMN "MC_TABLE_LOG"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "MC_TABLE_LOG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "MC_TABLE_LOG"."CREATOR_ID" IS '创建人 id';
COMMENT ON COLUMN "MC_TABLE_LOG"."DATA_QUALITY" IS '数据质量';
COMMENT ON COLUMN "MC_TABLE_LOG"."DATA_TYPE" IS '数据类型;数据类型 1：预发布 2：采集，预留字段，暂时不用';
COMMENT ON COLUMN "MC_TABLE_LOG"."DATASOURCE_ID" IS '数据源 id;冗余字段';
COMMENT ON COLUMN "MC_TABLE_LOG"."DB_ID" IS '库 id';
COMMENT ON COLUMN "MC_TABLE_LOG"."DB_NAME" IS '数据库名';
COMMENT ON COLUMN "MC_TABLE_LOG"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';
COMMENT ON COLUMN "MC_TABLE_LOG"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "MC_TABLE_LOG"."ID" IS 'ID';
COMMENT ON COLUMN "MC_TABLE_LOG"."INSTANCE_ID" IS '实例 ID';
COMMENT ON COLUMN "MC_TABLE_LOG"."MASTER_FLAG" IS '是否主表;0：否，1：是';
COMMENT ON COLUMN "MC_TABLE_LOG"."REMARK" IS '备注';
COMMENT ON COLUMN "MC_TABLE_LOG"."SAFETY_LEVEL_ID" IS '安全等级 id';
COMMENT ON COLUMN "MC_TABLE_LOG"."SCHEMA_NAME" IS '模式名;可空';
COMMENT ON COLUMN "MC_TABLE_LOG"."STORAGE_SIZE" IS '存储大小';
COMMENT ON COLUMN "MC_TABLE_LOG"."STORAGE_TYPE" IS '存储类型';
COMMENT ON COLUMN "MC_TABLE_LOG"."TABLE_COMMENT" IS '表注释/表描述（表中文名称）';
COMMENT ON COLUMN "MC_TABLE_LOG"."TABLE_ID" IS '表 id';
COMMENT ON COLUMN "MC_TABLE_LOG"."TABLE_NAME" IS '表名称（表英文名称）';
COMMENT ON COLUMN "MC_TABLE_LOG"."TASK_ID" IS '采集任务 id;预留字段，暂时不用';
COMMENT ON COLUMN "MC_TABLE_LOG"."TECH_LEADER" IS '技术责任人';
COMMENT ON COLUMN "MC_TABLE_LOG"."TECH_LEADER_PHONE" IS '技术责任人电话';
COMMENT ON COLUMN "MC_TABLE_LOG"."TEMP_FLAG" IS '是否临时表;0：否，1：是';
COMMENT ON COLUMN "MC_TABLE_LOG"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "MC_TABLE_LOG"."UPDATE_MSG" IS '变更说明';
COMMENT ON COLUMN "MC_TABLE_LOG"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "MC_TABLE_LOG"."UPDATE_TYPE" IS '变更类型';
COMMENT ON COLUMN "MC_TABLE_LOG"."UPDATER_ID" IS '更新人 id';
COMMENT ON COLUMN "MC_TABLE_LOG"."VALID_FLAG" IS '是否有效;0：无效，1：有效';
COMMENT ON COLUMN "MC_TABLE_LOG"."VERSION" IS '版本';


CREATE TABLE "MC_TASK"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "SOURCE_SYSTEM_ID" BIGINT NOT NULL,
    "SOURCE_SYSTEM_NAME" VARCHAR2(128) NOT NULL,
    "NAME" VARCHAR2(128) NOT NULL,
    "DATASOURCE_ID" BIGINT NOT NULL,
    "DB_TYPE" VARCHAR2(32) NOT NULL,
    "LEADER" BIGINT,
    "LEADER_PHONE" VARCHAR2(32),
    "COLLECTION_MODE" VARCHAR2(10) DEFAULT '1' NOT NULL,
    "COLLECTION_SCOPE" VARCHAR2(10) DEFAULT '1' NOT NULL,
    "STATUS" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "VALID_FLAG" VARCHAR2(1) DEFAULT '1' NOT NULL,
    "DEL_FLAG" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "CREATE_BY" VARCHAR2(32),
    "CREATOR_ID" BIGINT,
    "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_BY" VARCHAR2(32),
    "UPDATER_ID" BIGINT,
    "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "REMARK" VARCHAR2(512),
    "DESCRIPTION" VARCHAR2(512),
    "COLLECT_TYPE" SMALLINT DEFAULT 1 NOT NULL,
    "BLACKLIST" CLOB,
    "RESPONSIBLE_DEPT" BIGINT,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "MC_TASK" IS '采集任务表';
COMMENT ON COLUMN "MC_TASK"."BLACKLIST" IS '采集黑名单';
COMMENT ON COLUMN "MC_TASK"."COLLECT_TYPE" IS '采集任务类型：1-采集，2-DDL';
COMMENT ON COLUMN "MC_TASK"."COLLECTION_MODE" IS '采集模式;1:增量 2:全量 3:CDC 捕获';
COMMENT ON COLUMN "MC_TASK"."COLLECTION_SCOPE" IS '采集范围;1:自定义库  2:整个数据源（整个数据源时采集范围表中不需要存储数据，每次同步时现查即可）';
COMMENT ON COLUMN "MC_TASK"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "MC_TASK"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "MC_TASK"."CREATOR_ID" IS '创建人id';
COMMENT ON COLUMN "MC_TASK"."DATASOURCE_ID" IS '数据连接id';
COMMENT ON COLUMN "MC_TASK"."DB_TYPE" IS '数据库类型;冗余字段';
COMMENT ON COLUMN "MC_TASK"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';
COMMENT ON COLUMN "MC_TASK"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "MC_TASK"."SOURCE_SYSTEM_NAME" IS '来源系统名称';
COMMENT ON COLUMN "MC_TASK"."SOURCE_SYSTEM_ID" IS '来源系统id';
COMMENT ON COLUMN "MC_TASK"."ID" IS 'ID';
COMMENT ON COLUMN "MC_TASK"."LEADER" IS '责任人';
COMMENT ON COLUMN "MC_TASK"."LEADER_PHONE" IS '责任人电话';
COMMENT ON COLUMN "MC_TASK"."NAME" IS '任务名称';
COMMENT ON COLUMN "MC_TASK"."REMARK" IS '备注';
COMMENT ON COLUMN "MC_TASK"."RESPONSIBLE_DEPT" IS '所属部门';
COMMENT ON COLUMN "MC_TASK"."STATUS" IS '任务状态;0:下线 1:上线';
COMMENT ON COLUMN "MC_TASK"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "MC_TASK"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "MC_TASK"."UPDATER_ID" IS '更新人id';
COMMENT ON COLUMN "MC_TASK"."VALID_FLAG" IS '是否有效;0：无效，1：有效';


CREATE TABLE "MC_TASK_INSTANCE"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "SOURCE_SYSTEM_ID" BIGINT NOT NULL,
    "SOURCE_SYSTEM_NAME" VARCHAR2(128) NOT NULL,
    "TASK_ID" BIGINT NOT NULL,
    "COLLECTION_MODE" VARCHAR2(10) DEFAULT '1' NOT NULL,
    "COLLECTION_SCOPE" VARCHAR2(10) DEFAULT '1' NOT NULL,
    "TOTAL_COUNT" INTEGER DEFAULT 0 NOT NULL,
    "SUCCESS_COUNT" INTEGER DEFAULT 0,
    "FAIL_COUNT" INTEGER DEFAULT 0,
    "FAIL_CAUSE" VARCHAR2(512),
    "ADD_COUNT" INTEGER DEFAULT 0,
    "DEL_COUNT" INTEGER DEFAULT 0,
    "UPDATE_COUNT" INTEGER DEFAULT 0,
    "START_TIME" DATETIME(6) NOT NULL,
    "END_TIME" DATETIME(6),
    "DURATION" INTEGER DEFAULT 0,
    "STATUS" VARCHAR2(10) DEFAULT 1 NOT NULL,
    "VALID_FLAG" VARCHAR2(1) DEFAULT 1 NOT NULL,
    "DEL_FLAG" VARCHAR2(1) NOT NULL,
    "CREATE_BY" VARCHAR2(32),
    "CREATOR_ID" BIGINT,
    "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_BY" VARCHAR2(32),
    "UPDATER_ID" BIGINT,
    "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "REMARK" VARCHAR2(512),
    "DESCRIPTION" VARCHAR2(512),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "MC_TASK_INSTANCE" IS '采集任务实例表';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."ADD_COUNT" IS '新增数量';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."COLLECTION_MODE" IS '采集模式;1:增量 2:全量 3:CDC 捕获';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."COLLECTION_SCOPE" IS '采集范围;1:自定义库  2:整个数据源（整个数据源时采集范围表中不需要存储数据，每次同步时现查即可）';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."CREATOR_ID" IS '创建人id';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."DEL_COUNT" IS '删减数量';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."SOURCE_SYSTEM_NAME" IS '来源系统名称';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."SOURCE_SYSTEM_ID" IS '来源系统id';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."DURATION" IS '耗时;单位：秒';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."END_TIME" IS '结束时间';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."FAIL_CAUSE" IS '失败原因;任务的失败原因和某个表采集是否与否无关';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."FAIL_COUNT" IS '采集表失败数量';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."ID" IS 'ID';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."REMARK" IS '备注';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."START_TIME" IS '开始时间';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."STATUS" IS '状态;1：正在执行 2：失败 9：成功';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."SUCCESS_COUNT" IS '采集表成功数量';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."TASK_ID" IS '采集任务id';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."TOTAL_COUNT" IS '采集表总数量';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."UPDATE_COUNT" IS '变更数量';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."UPDATER_ID" IS '更新人id';
COMMENT ON COLUMN "MC_TASK_INSTANCE"."VALID_FLAG" IS '是否有效;0：无效，1：有效';


CREATE TABLE "MC_TASK_INSTANCE_LOG"
(
    "TASK_INSTANCE_ID" BIGINT NOT NULL,
    "TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "TASK_ID" BIGINT NOT NULL,
    "LOG_CONTENT" TEXT NOT NULL,
    "VALID_FLAG" VARCHAR2(1) DEFAULT '1' NOT NULL,
    "DEL_FLAG" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "CREATE_BY" VARCHAR2(32),
    "CREATOR_ID" BIGINT,
    "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_BY" VARCHAR2(32),
    "UPDATER_ID" BIGINT,
    "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "REMARK" VARCHAR2(512),
    NOT CLUSTER PRIMARY KEY("TASK_INSTANCE_ID", "TIME")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "MC_TASK_INSTANCE_LOG" IS '采集任务实例-日志表';
COMMENT ON COLUMN "MC_TASK_INSTANCE_LOG"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "MC_TASK_INSTANCE_LOG"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "MC_TASK_INSTANCE_LOG"."CREATOR_ID" IS '创建人id';
COMMENT ON COLUMN "MC_TASK_INSTANCE_LOG"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';
COMMENT ON COLUMN "MC_TASK_INSTANCE_LOG"."LOG_CONTENT" IS '日志内容';
COMMENT ON COLUMN "MC_TASK_INSTANCE_LOG"."REMARK" IS '备注';
COMMENT ON COLUMN "MC_TASK_INSTANCE_LOG"."TASK_ID" IS '任务id;采集任务的id';
COMMENT ON COLUMN "MC_TASK_INSTANCE_LOG"."TASK_INSTANCE_ID" IS '任务实例id';
COMMENT ON COLUMN "MC_TASK_INSTANCE_LOG"."TIME" IS '时间';
COMMENT ON COLUMN "MC_TASK_INSTANCE_LOG"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "MC_TASK_INSTANCE_LOG"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "MC_TASK_INSTANCE_LOG"."UPDATER_ID" IS '更新人id';
COMMENT ON COLUMN "MC_TASK_INSTANCE_LOG"."VALID_FLAG" IS '是否有效;0：无效，1：有效';


CREATE TABLE "MC_TASK_SCHEDULER"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "TASK_ID" BIGINT NOT NULL,
    "JOB_ID" BIGINT,
    "START_TIME" DATETIME(6),
    "END_TIME" DATETIME(6),
    "TIMEZONE_ID" VARCHAR2(128) DEFAULT 'Asia/Shanghai',
    "CRON_EXPRESSION" VARCHAR2(32) NOT NULL,
    "FAILURE_STRATEGY" VARCHAR2(1) DEFAULT '1',
    "STATUS" VARCHAR2(10) DEFAULT '0' NOT NULL,
    "REMARK" VARCHAR2(512),
    "VALID_FLAG" VARCHAR2(1) DEFAULT '1' NOT NULL,
    "DEL_FLAG" VARCHAR2(1) DEFAULT '0' NOT NULL,
    "CREATE_BY" VARCHAR2(32),
    "CREATOR_ID" BIGINT,
    "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_BY" VARCHAR2(32),
    "UPDATER_ID" BIGINT,
    "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "MC_TASK_SCHEDULER" IS '数据集成调度信息';
COMMENT ON COLUMN "MC_TASK_SCHEDULER"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "MC_TASK_SCHEDULER"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "MC_TASK_SCHEDULER"."CREATOR_ID" IS '创建人id';
COMMENT ON COLUMN "MC_TASK_SCHEDULER"."CRON_EXPRESSION" IS 'cron表达式';
COMMENT ON COLUMN "MC_TASK_SCHEDULER"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';
COMMENT ON COLUMN "MC_TASK_SCHEDULER"."END_TIME" IS '结束时间';
COMMENT ON COLUMN "MC_TASK_SCHEDULER"."FAILURE_STRATEGY" IS '失败策略;是否继续 0:否 1:是';
COMMENT ON COLUMN "MC_TASK_SCHEDULER"."ID" IS 'ID';
COMMENT ON COLUMN "MC_TASK_SCHEDULER"."JOB_ID" IS 'xxljobid;xxljobid';
COMMENT ON COLUMN "MC_TASK_SCHEDULER"."REMARK" IS '备注';
COMMENT ON COLUMN "MC_TASK_SCHEDULER"."START_TIME" IS '开始时间';
COMMENT ON COLUMN "MC_TASK_SCHEDULER"."STATUS" IS '调度状态;0:未上线，1:已上线 2:草稿';
COMMENT ON COLUMN "MC_TASK_SCHEDULER"."TASK_ID" IS '任务id';
COMMENT ON COLUMN "MC_TASK_SCHEDULER"."TIMEZONE_ID" IS '时区;直接默认 Asia/Shanghai';
COMMENT ON COLUMN "MC_TASK_SCHEDULER"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "MC_TASK_SCHEDULER"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "MC_TASK_SCHEDULER"."UPDATER_ID" IS '更新人id';
COMMENT ON COLUMN "MC_TASK_SCHEDULER"."VALID_FLAG" IS '是否有效;0：无效，1：有效';


CREATE TABLE "MC_TASK_SCOPE"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "TASK_ID" BIGINT NOT NULL,
    "DB_NAME" VARCHAR2(64) NOT NULL,
    "SCHEMA_NAME" VARCHAR2(64),
    "VALID_FLAG" VARCHAR2(1) DEFAULT 1 NOT NULL,
    "DEL_FLAG" VARCHAR2(1) DEFAULT 0 NOT NULL,
    "CREATE_BY" VARCHAR2(32),
    "CREATOR_ID" BIGINT,
    "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_BY" VARCHAR2(32),
    "UPDATER_ID" BIGINT,
    "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "REMARK" VARCHAR2(512),
    "DESCRIPTION" VARCHAR2(512),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "MC_TASK_SCOPE" IS '采集范围表';
COMMENT ON COLUMN "MC_TASK_SCOPE"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "MC_TASK_SCOPE"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "MC_TASK_SCOPE"."CREATOR_ID" IS '创建人id';
COMMENT ON COLUMN "MC_TASK_SCOPE"."DB_NAME" IS '数据库名称';
COMMENT ON COLUMN "MC_TASK_SCOPE"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';
COMMENT ON COLUMN "MC_TASK_SCOPE"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "MC_TASK_SCOPE"."ID" IS 'ID';
COMMENT ON COLUMN "MC_TASK_SCOPE"."REMARK" IS '备注';
COMMENT ON COLUMN "MC_TASK_SCOPE"."SCHEMA_NAME" IS '模式名';
COMMENT ON COLUMN "MC_TASK_SCOPE"."TASK_ID" IS '任务id;采集任务id';
COMMENT ON COLUMN "MC_TASK_SCOPE"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "MC_TASK_SCOPE"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "MC_TASK_SCOPE"."UPDATER_ID" IS '更新人id';
COMMENT ON COLUMN "MC_TASK_SCOPE"."VALID_FLAG" IS '是否有效;0：无效，1：有效';
