CREATE TABLE "QDATA"."DM_DATA_DOMAIN"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "NAME" VARCHAR2(64) NOT NULL,
 "ENG_NAME" VARCHAR2(32) NOT NULL,
 "OWNER_USER_ID" BIGINT NOT NULL,
 "DESCRIPTION" VARCHAR2(1024) NULL,
 "VALID_FLAG" VARCHAR2(1) DEFAULT '1'
 NOT NULL,
 "DEL_FLAG" VARCHAR2(1) DEFAULT '0'
 NOT NULL,
 "CREATE_BY" VARCHAR2(32) NULL,
 "CREATOR_ID" BIGINT NULL,
 "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP
 NOT NULL,
 "UPDATE_BY" VARCHAR2(32) NULL,
 "UPDATER_ID" BIGINT NULL,
 "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP
 NOT NULL,
 "REMARK" VARCHAR2(1024) NULL
);
CREATE TABLE "QDATA"."DM_DATA_LAYER"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "NAME" VARCHAR2(64) NOT NULL,
 "ENG_NAME" VARCHAR2(32) NOT NULL,
 "OWNER_USER_ID" BIGINT NOT NULL,
 "CATEGORY" CHAR(1) DEFAULT '1'
 NOT NULL,
 "DESCRIPTION" VARCHAR2(1024) NULL,
 "VALID_FLAG" VARCHAR2(1) DEFAULT '1'
 NOT NULL,
 "DEL_FLAG" VARCHAR2(1) DEFAULT '0'
 NOT NULL,
 "CREATE_BY" VARCHAR2(32) NULL,
 "CREATOR_ID" BIGINT NULL,
 "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP
 NOT NULL,
 "UPDATE_BY" VARCHAR2(32) NULL,
 "UPDATER_ID" BIGINT NULL,
 "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP
 NOT NULL,
 "REMARK" VARCHAR2(1024) NULL
);
CREATE TABLE "QDATA"."DM_DATA_LAYER_SPECIFICATION"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "DATA_LAYER_ID" BIGINT NOT NULL,
 "PREFIX_NAME" VARCHAR2(32) NOT NULL,
 "BUSINESS_ENG_NAME" VARCHAR2(32) NOT NULL,
 "OWNER_USER_ID" BIGINT NOT NULL,
 "STATUS" CHAR(1) DEFAULT '1'
 NOT NULL,
 "DESCRIPTION" VARCHAR2(1024) NULL,
 "VALID_FLAG" VARCHAR2(1) DEFAULT '1'
 NOT NULL,
 "DEL_FLAG" VARCHAR2(1) DEFAULT '0'
 NOT NULL,
 "CREATE_BY" VARCHAR2(32) NULL,
 "CREATOR_ID" BIGINT NULL,
 "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP
 NOT NULL,
 "UPDATE_BY" VARCHAR2(32) NULL,
 "UPDATER_ID" BIGINT NULL,
 "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP
 NOT NULL,
 "REMARK" VARCHAR2(1024) NULL,
 "序号" INT NULL
);
CREATE TABLE "QDATA"."DM_THEME_DOMAIN"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "CODE" VARCHAR2(128) NOT NULL,
 "NAME" VARCHAR2(64) NOT NULL,
 "ENG_NAME" VARCHAR2(32) NOT NULL,
 "PARENT_ID" BIGINT NULL,
 "OWNER_USER_ID" BIGINT NOT NULL,
 "DATA_LAYER_ID" BIGINT NOT NULL,
 "DESCRIPTION" VARCHAR2(1024) NULL,
 "VALID_FLAG" VARCHAR2(1) DEFAULT '1'
 NOT NULL,
 "DEL_FLAG" VARCHAR2(1) DEFAULT '0'
 NOT NULL,
 "CREATE_BY" VARCHAR2(32) NULL,
 "CREATOR_ID" BIGINT NULL,
 "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP
 NOT NULL,
 "UPDATE_BY" VARCHAR2(32) NULL,
 "UPDATER_ID" BIGINT NULL,
 "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP
 NOT NULL,
 "REMARK" VARCHAR2(1024) NULL
);

ALTER TABLE "QDATA"."DM_DATA_DOMAIN" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("ID") ;

ALTER TABLE "QDATA"."DM_DATA_LAYER" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("ID") ;

ALTER TABLE "QDATA"."DM_DATA_LAYER_SPECIFICATION" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("ID") ;

ALTER TABLE "QDATA"."DM_THEME_DOMAIN" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("ID") ;

COMMENT ON TABLE "QDATA"."DM_DATA_DOMAIN" IS '数据域管理';

COMMENT ON COLUMN "QDATA"."DM_DATA_DOMAIN"."CREATE_BY" IS '创建人';

COMMENT ON COLUMN "QDATA"."DM_DATA_DOMAIN"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "QDATA"."DM_DATA_DOMAIN"."CREATOR_ID" IS '创建人id';

COMMENT ON COLUMN "QDATA"."DM_DATA_DOMAIN"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';

COMMENT ON COLUMN "QDATA"."DM_DATA_DOMAIN"."DESCRIPTION" IS '描述';

COMMENT ON COLUMN "QDATA"."DM_DATA_DOMAIN"."ENG_NAME" IS '英文缩写';

COMMENT ON COLUMN "QDATA"."DM_DATA_DOMAIN"."ID" IS 'ID';

COMMENT ON COLUMN "QDATA"."DM_DATA_DOMAIN"."NAME" IS '名称';

COMMENT ON COLUMN "QDATA"."DM_DATA_DOMAIN"."OWNER_USER_ID" IS '负责人ID';

COMMENT ON COLUMN "QDATA"."DM_DATA_DOMAIN"."REMARK" IS '备注';

COMMENT ON COLUMN "QDATA"."DM_DATA_DOMAIN"."UPDATE_BY" IS '更新人';

COMMENT ON COLUMN "QDATA"."DM_DATA_DOMAIN"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "QDATA"."DM_DATA_DOMAIN"."UPDATER_ID" IS '更新人id';

COMMENT ON COLUMN "QDATA"."DM_DATA_DOMAIN"."VALID_FLAG" IS '是否有效;0：无效，1：有效';

COMMENT ON TABLE "QDATA"."DM_DATA_LAYER" IS '数仓分层管理';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER"."CATEGORY" IS '分类;1：贴源层 2:公共层 3:应用层(字典：dm_data_layer_category)';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER"."CREATE_BY" IS '创建人';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER"."CREATOR_ID" IS '创建人id';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER"."DESCRIPTION" IS '描述';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER"."ENG_NAME" IS '英文缩写';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER"."ID" IS 'ID';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER"."NAME" IS '名称';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER"."OWNER_USER_ID" IS '负责人ID';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER"."REMARK" IS '备注';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER"."UPDATE_BY" IS '更新人';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER"."UPDATER_ID" IS '更新人id';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER"."VALID_FLAG" IS '是否有效;0：无效，1：有效';

COMMENT ON TABLE "QDATA"."DM_DATA_LAYER_SPECIFICATION" IS '数仓分层-规范管理';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER_SPECIFICATION"."BUSINESS_ENG_NAME" IS '业务大类英文缩写';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER_SPECIFICATION"."CREATE_BY" IS '创建人';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER_SPECIFICATION"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER_SPECIFICATION"."CREATOR_ID" IS '创建人id';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER_SPECIFICATION"."DATA_LAYER_ID" IS '数仓分层ID';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER_SPECIFICATION"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER_SPECIFICATION"."DESCRIPTION" IS '描述';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER_SPECIFICATION"."ID" IS 'ID';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER_SPECIFICATION"."OWNER_USER_ID" IS '负责人ID';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER_SPECIFICATION"."PREFIX_NAME" IS '表前缀';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER_SPECIFICATION"."REMARK" IS '备注';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER_SPECIFICATION"."STATUS" IS '状态;0：关闭，1：开启';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER_SPECIFICATION"."UPDATE_BY" IS '更新人';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER_SPECIFICATION"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER_SPECIFICATION"."UPDATER_ID" IS '更新人id';

COMMENT ON COLUMN "QDATA"."DM_DATA_LAYER_SPECIFICATION"."VALID_FLAG" IS '是否有效;0：无效，1：有效';

COMMENT ON TABLE "QDATA"."DM_THEME_DOMAIN" IS '主题域管理';

COMMENT ON COLUMN "QDATA"."DM_THEME_DOMAIN"."CODE" IS '层级编码';

COMMENT ON COLUMN "QDATA"."DM_THEME_DOMAIN"."CREATE_BY" IS '创建人';

COMMENT ON COLUMN "QDATA"."DM_THEME_DOMAIN"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "QDATA"."DM_THEME_DOMAIN"."CREATOR_ID" IS '创建人id';

COMMENT ON COLUMN "QDATA"."DM_THEME_DOMAIN"."DATA_LAYER_ID" IS '数仓分层ID';

COMMENT ON COLUMN "QDATA"."DM_THEME_DOMAIN"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';

COMMENT ON COLUMN "QDATA"."DM_THEME_DOMAIN"."DESCRIPTION" IS '描述';

COMMENT ON COLUMN "QDATA"."DM_THEME_DOMAIN"."ENG_NAME" IS '英文缩写';

COMMENT ON COLUMN "QDATA"."DM_THEME_DOMAIN"."ID" IS 'ID';

COMMENT ON COLUMN "QDATA"."DM_THEME_DOMAIN"."NAME" IS '名称';

COMMENT ON COLUMN "QDATA"."DM_THEME_DOMAIN"."OWNER_USER_ID" IS '负责人ID';

COMMENT ON COLUMN "QDATA"."DM_THEME_DOMAIN"."PARENT_ID" IS '关联上级ID';

COMMENT ON COLUMN "QDATA"."DM_THEME_DOMAIN"."REMARK" IS '备注';

COMMENT ON COLUMN "QDATA"."DM_THEME_DOMAIN"."UPDATE_BY" IS '更新人';

COMMENT ON COLUMN "QDATA"."DM_THEME_DOMAIN"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "QDATA"."DM_THEME_DOMAIN"."UPDATER_ID" IS '更新人id';

COMMENT ON COLUMN "QDATA"."DM_THEME_DOMAIN"."VALID_FLAG" IS '是否有效;0：无效，1：有效';
