-- 创建 版本跟踪 表
CREATE TABLE SYSTEM_VERSION_TRACK(
    ID BIGINT IDENTITY(1,1) ,
    NAME VARCHAR2(128),
    CURR_VERSION VARCHAR2(128) NOT NULL,
    DESCRIPTION VARCHAR2(512),
    AUTHOR VARCHAR2(128),
    DEL_FLAG VARCHAR2(1) NOT NULL DEFAULT  0,
    CREATE_BY VARCHAR2(32),
    CREATOR_ID BIGINT,
    CREATE_TIME DATETIME NOT NULL DEFAULT  CURRENT_TIMESTAMP,
    UPDATE_BY VARCHAR2(32),
    UPDATER_ID BIGINT,
    UPDATE_TIME DATETIME NOT NULL DEFAULT  CURRENT_TIMESTAMP,
    REMARK VARCHAR2(512),
    PRIMARY KEY (ID)
);

COMMENT ON TABLE SYSTEM_VERSION_TRACK IS '版本跟踪';
COMMENT ON COLUMN SYSTEM_VERSION_TRACK.ID IS 'ID';
COMMENT ON COLUMN SYSTEM_VERSION_TRACK.NAME IS '项目名称';
COMMENT ON COLUMN SYSTEM_VERSION_TRACK.CURR_VERSION IS '项目版本号';
COMMENT ON COLUMN SYSTEM_VERSION_TRACK.DESCRIPTION IS '描述';
COMMENT ON COLUMN SYSTEM_VERSION_TRACK.AUTHOR IS '作者';
COMMENT ON COLUMN SYSTEM_VERSION_TRACK.DEL_FLAG IS '删除标志;1：已删除，0：未删除';
COMMENT ON COLUMN SYSTEM_VERSION_TRACK.CREATE_BY IS '创建人';
COMMENT ON COLUMN SYSTEM_VERSION_TRACK.CREATOR_ID IS '创建人id';
COMMENT ON COLUMN SYSTEM_VERSION_TRACK.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN SYSTEM_VERSION_TRACK.UPDATE_BY IS '更新人';
COMMENT ON COLUMN SYSTEM_VERSION_TRACK.UPDATER_ID IS '更新人id';
COMMENT ON COLUMN SYSTEM_VERSION_TRACK.UPDATE_TIME IS '更新时间';
COMMENT ON COLUMN SYSTEM_VERSION_TRACK.REMARK IS '备注';
