CREATE TABLE "DM_BUSINESS_CATEGORY"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "NAME" VARCHAR2(128) NOT NULL,
    "PARENT_ID" BIGINT,
    "SORT_ORDER" INTEGER DEFAULT 0 NOT NULL,
    "DESCRIPTION" VARCHAR2(512),
    "ENG_NAME" VARCHAR2(128),
    "OWNER_PHONE" VARCHAR2(128),
    "OWNER_ID" BIGINT,
    "DOMAIN_ID" BIGINT,
    "VALID_FLAG" VARCHAR2(1) DEFAULT 1 NOT NULL,
    "DEL_FLAG" VARCHAR2(1) DEFAULT 0 NOT NULL,
    "CREATE_BY" VARCHAR2(32),
    "CREATOR_ID" BIGINT,
    "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_BY" VARCHAR2(32),
    "UPDATER_ID" BIGINT,
    "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "REMARK" VARCHAR2(512),
    "CODE" VARCHAR2(128),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DM_BUSINESS_CATEGORY" IS '业务分类';
COMMENT ON COLUMN "DM_BUSINESS_CATEGORY"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "DM_BUSINESS_CATEGORY"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DM_BUSINESS_CATEGORY"."CREATOR_ID" IS '创建人id';
COMMENT ON COLUMN "DM_BUSINESS_CATEGORY"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';
COMMENT ON COLUMN "DM_BUSINESS_CATEGORY"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "DM_BUSINESS_CATEGORY"."DOMAIN_ID" IS '数据域ID';
COMMENT ON COLUMN "DM_BUSINESS_CATEGORY"."ENG_NAME" IS '英文缩写名';
COMMENT ON COLUMN "DM_BUSINESS_CATEGORY"."ID" IS 'ID';
COMMENT ON COLUMN "DM_BUSINESS_CATEGORY"."NAME" IS '业务分类名称';
COMMENT ON COLUMN "DM_BUSINESS_CATEGORY"."OWNER_ID" IS '负责人ID';
COMMENT ON COLUMN "DM_BUSINESS_CATEGORY"."OWNER_PHONE" IS '负责人手机号';
COMMENT ON COLUMN "DM_BUSINESS_CATEGORY"."PARENT_ID" IS '关联上级ID';
COMMENT ON COLUMN "DM_BUSINESS_CATEGORY"."REMARK" IS '备注';
COMMENT ON COLUMN "DM_BUSINESS_CATEGORY"."SORT_ORDER" IS '排序';
COMMENT ON COLUMN "DM_BUSINESS_CATEGORY"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "DM_BUSINESS_CATEGORY"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "DM_BUSINESS_CATEGORY"."UPDATER_ID" IS '更新人id';
COMMENT ON COLUMN "DM_BUSINESS_CATEGORY"."VALID_FLAG" IS '是否有效;0：无效，1：有效';


CREATE TABLE "DM_BUSINESS_DOMAIN_REL"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "BUSINESS_CATEGORY_ID" BIGINT NOT NULL,
    "DATA_DOMAIN_ID" BIGINT NOT NULL,
    "BUSINESS_CATEGORY_NAME" VARCHAR2(128),
    "DATA_DOMAIN_NAME" VARCHAR2(128),
    "SORT_ORDER" INTEGER DEFAULT 0 NOT NULL,
    "DESCRIPTION" VARCHAR2(512),
    "VALID_FLAG" VARCHAR2(1) DEFAULT 1 NOT NULL,
    "DEL_FLAG" VARCHAR2(1) DEFAULT 0 NOT NULL,
    "CREATE_BY" VARCHAR2(32),
    "CREATOR_ID" BIGINT,
    "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_BY" VARCHAR2(32),
    "UPDATER_ID" BIGINT,
    "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "REMARK" VARCHAR2(512),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DM_BUSINESS_DOMAIN_REL" IS '业务分类数据域关联关系';
COMMENT ON COLUMN "DM_BUSINESS_DOMAIN_REL"."BUSINESS_CATEGORY_ID" IS '业务分类ID';
COMMENT ON COLUMN "DM_BUSINESS_DOMAIN_REL"."BUSINESS_CATEGORY_NAME" IS '业务分类名称';
COMMENT ON COLUMN "DM_BUSINESS_DOMAIN_REL"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "DM_BUSINESS_DOMAIN_REL"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DM_BUSINESS_DOMAIN_REL"."CREATOR_ID" IS '创建人id';
COMMENT ON COLUMN "DM_BUSINESS_DOMAIN_REL"."DATA_DOMAIN_ID" IS '数据域ID';
COMMENT ON COLUMN "DM_BUSINESS_DOMAIN_REL"."DATA_DOMAIN_NAME" IS '数据域名称';
COMMENT ON COLUMN "DM_BUSINESS_DOMAIN_REL"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';
COMMENT ON COLUMN "DM_BUSINESS_DOMAIN_REL"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "DM_BUSINESS_DOMAIN_REL"."ID" IS 'ID';
COMMENT ON COLUMN "DM_BUSINESS_DOMAIN_REL"."REMARK" IS '备注';
COMMENT ON COLUMN "DM_BUSINESS_DOMAIN_REL"."SORT_ORDER" IS '排序';
COMMENT ON COLUMN "DM_BUSINESS_DOMAIN_REL"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "DM_BUSINESS_DOMAIN_REL"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "DM_BUSINESS_DOMAIN_REL"."UPDATER_ID" IS '更新人id';
COMMENT ON COLUMN "DM_BUSINESS_DOMAIN_REL"."VALID_FLAG" IS '是否有效;0：无效，1：有效';

-- 逻辑模型新增字段
ALTER TABLE "DP_MODEL" ADD(
TABLE_TYPE VARCHAR2(10)DEFAULT'1',
DATA_LAYER_ID BIGINT,
DATA_DOMAIN_ID BIGINT,
BUSINESS_CATEGORY_ID BIGINT,
BUSINESS_CATEGORY_CODE VARCHAR2(128),
THEME_DOMAIN_ID BIGINT,
THEME_DOMAIN_CODE VARCHAR2(128),
TABLE_CASE VARCHAR2(10)DEFAULT '1'
);

COMMENT ON COLUMN "DP_MODEL".TABLE_TYPE IS '表类型;1:明细表 2:汇总表 3:维度表 4:应用表';
COMMENT ON COLUMN "DP_MODEL".DATA_LAYER_ID IS '数仓分层id';
COMMENT ON COLUMN "DP_MODEL".DATA_DOMAIN_ID IS '数据分域id;只有表类型为非应用表是才有值';
COMMENT ON COLUMN "DP_MODEL".BUSINESS_CATEGORY_ID IS '业务分类id;只有表类型为非应用表是才有值';
COMMENT ON COLUMN "DP_MODEL".BUSINESS_CATEGORY_CODE IS '业务分类层级编码';
COMMENT ON COLUMN "DP_MODEL".THEME_DOMAIN_ID IS '所属主题id（主题规划）;只有表类型为应用表是才有值';
COMMENT ON COLUMN "DP_MODEL".THEME_DOMAIN_CODE IS '所属主题层级编码';
COMMENT ON COLUMN "DP_MODEL".TABLE_CASE IS '表名大小写;1：大写 2：小写';

-- 逻辑模型新增字段
ALTER TABLE "DA_ASSET" ADD(
TABLE_TYPE VARCHAR2(10)DEFAULT'1',
DATA_LAYER_ID BIGINT,
DATA_DOMAIN_ID BIGINT,
BUSINESS_CATEGORY_ID BIGINT,
BUSINESS_CATEGORY_CODE VARCHAR2(128),
THEME_DOMAIN_ID BIGINT,
THEME_DOMAIN_CODE VARCHAR2(128),
TABLE_CASE VARCHAR2(10)DEFAULT '1',
TABLE_ID VARCHAR2(128)
);

COMMENT ON COLUMN "DA_ASSET".TABLE_TYPE IS '表类型;1:明细表 2:汇总表 3:维度表 4:应用表';
COMMENT ON COLUMN "DA_ASSET".DATA_LAYER_ID IS '数仓分层id';
COMMENT ON COLUMN "DA_ASSET".DATA_DOMAIN_ID IS '数据分域id;只有表类型为非应用表是才有值';
COMMENT ON COLUMN "DA_ASSET".BUSINESS_CATEGORY_ID IS '业务分类id;只有表类型为非应用表是才有值';
COMMENT ON COLUMN "DA_ASSET".BUSINESS_CATEGORY_CODE IS '业务分类层级编码';
COMMENT ON COLUMN "DA_ASSET".THEME_DOMAIN_ID IS '所属主题id（主题规划）;只有表类型为应用表是才有值';
COMMENT ON COLUMN "DA_ASSET".THEME_DOMAIN_CODE IS '所属主题层级编码';
COMMENT ON COLUMN "DA_ASSET".TABLE_CASE IS '表名大小写;1：大写 2：小写';
COMMENT ON COLUMN "DA_ASSET".TABLE_ID IS '元数据表id';

ALTER TABLE "DA_ASSET" MODIFY CAT_CODE VARCHAR2(256) NULL;

ALTER TABLE "DP_MODEL" MODIFY "CAT_CODE" VARCHAR2(128) NULL;

ALTER TABLE "DP_MODEL_MATERIALIZED" ADD RELEASE_MODE CHAR(1)DEFAULT '1' NULL;


CREATE TABLE "DG_DATA_CATEGORY"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "CAT_ID" BIGINT NOT NULL,
    "CAT_CODE" VARCHAR2(32) NOT NULL,
    "NAME" VARCHAR2(128) NOT NULL,
    "SHORT_NAME" VARCHAR2(128),
    "DATA_LEVEL_ID" BIGINT DEFAULT 0 NOT NULL,
    "PRIORITY" VARCHAR2(32) DEFAULT 'MEDIUM',
    "DESCRIPTION" VARCHAR2(512),
    "VALID_FLAG" VARCHAR2(1) DEFAULT 1 NOT NULL,
    "DEL_FLAG" VARCHAR2(1) DEFAULT 0 NOT NULL,
    "CREATE_BY" VARCHAR2(32),
    "CREATOR_ID" BIGINT,
    "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_BY" VARCHAR2(32),
    "UPDATER_ID" BIGINT,
    "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "REMARK" VARCHAR2(512),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DG_DATA_CATEGORY" IS '数据分类';
COMMENT ON COLUMN "DG_DATA_CATEGORY"."ID" IS 'ID';
COMMENT ON COLUMN "DG_DATA_CATEGORY"."CAT_ID" IS '类目id';
COMMENT ON COLUMN "DG_DATA_CATEGORY"."CAT_CODE" IS '类目编码';
COMMENT ON COLUMN "DG_DATA_CATEGORY"."NAME" IS '分类名称';
COMMENT ON COLUMN "DG_DATA_CATEGORY"."SHORT_NAME" IS '分类名称缩写名';
COMMENT ON COLUMN "DG_DATA_CATEGORY"."DATA_LEVEL_ID" IS '数据分级';
COMMENT ON COLUMN "DG_DATA_CATEGORY"."PRIORITY" IS '任务优先级;HIGHEST,HIGH,MEDIUM,LOW,LOWEST';
COMMENT ON COLUMN "DG_DATA_CATEGORY"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "DG_DATA_CATEGORY"."VALID_FLAG" IS '是否有效;0：无效，1：有效';
COMMENT ON COLUMN "DG_DATA_CATEGORY"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';
COMMENT ON COLUMN "DG_DATA_CATEGORY"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "DG_DATA_CATEGORY"."CREATOR_ID" IS '创建人id';
COMMENT ON COLUMN "DG_DATA_CATEGORY"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DG_DATA_CATEGORY"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "DG_DATA_CATEGORY"."UPDATER_ID" IS '更新人id';
COMMENT ON COLUMN "DG_DATA_CATEGORY"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "DG_DATA_CATEGORY"."REMARK" IS '备注';


CREATE TABLE "DG_DESENSITIZE_ASSETCOLUMN"
(
    "ID" BIGINT IDENTITY(1, 1) NOT NULL,
    "ASSET_ID" BIGINT NOT NULL,
    "ASSETCOLUMN_ID" BIGINT NOT NULL,
    "DATA_CATEGORY_ID" BIGINT NOT NULL,
    "SORT_ORDER" INTEGER DEFAULT 0 NOT NULL,
    "DESCRIPTION" VARCHAR2(512),
    "VALID_FLAG" VARCHAR2(1) DEFAULT 1 NOT NULL,
    "DEL_FLAG" VARCHAR2(1) DEFAULT 0 NOT NULL,
    "CREATE_BY" VARCHAR2(32),
    "CREATOR_ID" BIGINT,
    "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "UPDATE_BY" VARCHAR2(32),
    "UPDATER_ID" BIGINT,
    "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "REMARK" VARCHAR2(512),
    NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

COMMENT ON TABLE "DG_DESENSITIZE_ASSETCOLUMN" IS '脱敏清单关联关系';
COMMENT ON COLUMN "DG_DESENSITIZE_ASSETCOLUMN"."ID" IS 'ID';
COMMENT ON COLUMN "DG_DESENSITIZE_ASSETCOLUMN"."ASSET_ID" IS '资产ID';
COMMENT ON COLUMN "DG_DESENSITIZE_ASSETCOLUMN"."ASSETCOLUMN_ID" IS '资产字段ID';
COMMENT ON COLUMN "DG_DESENSITIZE_ASSETCOLUMN"."DATA_CATEGORY_ID" IS '数据分类ID';
COMMENT ON COLUMN "DG_DESENSITIZE_ASSETCOLUMN"."SORT_ORDER" IS '排序';
COMMENT ON COLUMN "DG_DESENSITIZE_ASSETCOLUMN"."DESCRIPTION" IS '描述';
COMMENT ON COLUMN "DG_DESENSITIZE_ASSETCOLUMN"."VALID_FLAG" IS '是否有效;0：无效，1：有效';
COMMENT ON COLUMN "DG_DESENSITIZE_ASSETCOLUMN"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';
COMMENT ON COLUMN "DG_DESENSITIZE_ASSETCOLUMN"."CREATE_BY" IS '创建人';
COMMENT ON COLUMN "DG_DESENSITIZE_ASSETCOLUMN"."CREATOR_ID" IS '创建人id';
COMMENT ON COLUMN "DG_DESENSITIZE_ASSETCOLUMN"."CREATE_TIME" IS '创建时间';
COMMENT ON COLUMN "DG_DESENSITIZE_ASSETCOLUMN"."UPDATE_BY" IS '更新人';
COMMENT ON COLUMN "DG_DESENSITIZE_ASSETCOLUMN"."UPDATER_ID" IS '更新人id';
COMMENT ON COLUMN "DG_DESENSITIZE_ASSETCOLUMN"."UPDATE_TIME" IS '更新时间';
COMMENT ON COLUMN "DG_DESENSITIZE_ASSETCOLUMN"."REMARK" IS '备注';




