/*
 * Copyright © 2025-present Jiangsu Qiantong Technology Co., Ltd.
 *
 * This file is part of qData Data Middle Platform (Open Source Edition).
 *
 * qData is licensed under Apache License 2.0 with additional qData terms.
 * You may use qData for commercial purposes, but you may not remove, hide,
 * modify, or replace the qData logo, copyright notices, license notices,
 * or attribution information without a separate commercial license.
 *
 * White-label use, OEM distribution, rebranding, or presenting qData as
 * another product requires separate commercial authorization from
 * Jiangsu Qiantong Technology Co., Ltd.
 *
 * Business License: https://community.qdata.tech/business/policy.html
 * See the LICENSE file in the project root for full license information.
 */

package tech.qiantong.qdata.api.ds.api.etl;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * <P>
 * Description: Task save request DTO
 * </p>
 *
 * @author: FXB
 * @create: 2025-02-19 09:19
 **/
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DsTaskSaveReqDTO {

    /**
     * Task code (nullable)
     */
    Long processDefinitionCode;

    /**
     * Task name (required)
     */
    private String name;

    /**
     * Task description
     */
    private String description;

    /**
     * Execution type (required) PARALLEL, SERIAL_WAIT, SERIAL_DISCARD, SERIAL_PRIORITY
     */
    private String executionType;

    /**
     * Node definition JSON string (required)
     * Format as follows
     * [{
     * "id":12,
     * "name":"test",
     * "code":133455210749664,
     * "version":10,//version
     * "description":"",
     * "workerGroup": "default",//default "default"
     * "environmentCode":133155949418208,//default 133155949418208
     * "flag":"YES",//default "YES"
     * "isCache":"NO",//default "NO"
     * "taskParams":{"desc"},//JSON object, structure in the comment below, note: not a string
     * "taskPriority":"MEDIUM",//priority, default "MEDIUM"
     * "taskType":"SPARK"//node type: DATAX, SPARK, SQL, PROCEDURE (stored procedure), SUB_PROCESS (sub-task), etc.
     * }]
     * taskParams SPARK (cleaning)
     * {
     *     "localParams": [],//default []
     *     "rawScript": "",//default ""
     *     "resourceList": [],//default []
     *     "programType": "JAVA",//default "JAVA"
     *     "mainClass": "com.demo.WordCount",//defaults from config file ds.spark.main_jar
     *     "mainJar": {
     *         "resourceName": "file:/dolphinscheduler/default/resources/spart-demo-1.0.jar"//defaults from config file ds.spark.main_jar
     *     },
     *     "deployMode": "client",//default "client"
     *     "mainArgs": "write the data source, database/table info and rules JSON here",
     *     "master": "spark://qiantong100:7077",//defaults from config file ds.spark.master_url
     *     "driverCores": 1,//default 1
     *     "driverMemory": "512M",//default "512M"
     *     "numExecutors": 1,//default 1
     *     "executorMemory": "1G",//default 1G
     *     "executorCores": 1,//default 1
     *     "sqlExecutionType": "SCRIPT"//default "SCRIPT"
     * }
     * taskParams DATAX
     * {
     *     “localParams”: [],//default []
     *     “resourceList”:[],//default []
     *     “customConfig”: 0,//default []
     *     “customConfig”: 1,//hardcoded 1
     *     “json”: “{}”,//DATAX JSON string data, default 1024
     *     “xms”: 1,//default 1
     *     “xmx”: 1,//default 1
     *     “batchSize”:1024,//batch write size, nullable, defaults to 1024 when empty
     *     “preSql”: “”,//pre SQL, converted to array when generating datax JSON (split by semicolons)
     *     “postSql”: “”,//post SQL, converted to array when generating datax JSON (split by semicolons)
     *     //source and target table info below for frontend display
     *     “type”:1,//node type 1: input node 2: output node
     *     “datasource_id”:1,//source table datasource id, null for output nodes
     *     “asset_id”:1,//source table asset id, null for output nodes
     *     “table_name”:1,//source table name, auto-generated by backend for output nodes
     *     “columns”:[“ID”,”NAME”,”AGE”],//source table sync column list, auto-generated by backend for output nodes
     *     “target_datasource_id”:1,//target datasource id, null for input nodes
     *     “target_asset_id”:1,//target asset id, null for input nodes
     *     “target_table_name”:1,//target table name, auto-generated by backend for input nodes
     *     “target_columns”:[“ID”,”NAME”,”AGE”],//target table sync column list, auto-generated by backend for input nodes
     * }
     *
     * taskParams SQL (relational database)
     * {
     *     “localParams”: [],//default []
     *     “resourceList”: [],//default []
     *     “type”:”MYSQL”,//database type, currently supports MYSQL, ORACLE, DAMENG, KINGBASE
     *     “sql”:””,//SQL statement
     *     “sqlType”:””, // 0 query 1 non-query
     *     “preStatements”:[],//default []
     *     “postStatements”:[],//default []
     *     “displayRows”:10,//default 10
     *     “datasources”:{
     *         “type”:”MYSQL”,//database type, currently supports MYSQL, ORACLE, DAMENG, KINGBASE
     *         “host”:””,//ip
     *         “port”:1521,//port
     *         “userName”:””,//username
     *         “password”:””,//password
     *         “database”:””,//database name
     *         “connectType”:”ORACLE_SERVICE_NAME”//default “ORACLE_SERVICE_NAME”, only Oracle needs: ORACLE_SERVICE_NAME: service name, ORACLE_SID: SID
     *         “other”:{}//other database parameters, optional
     *     }
     * }
     *
     *
     * taskParams PROCEDURE (stored procedure)
     * {
     *     “localParams”: [],//default []
     *     “resourceList”: [],//default []
     *     “type”:”MYSQL”,//database type, currently supports MYSQL, ORACLE, DAMENG, KINGBASE
     *     “method”:”call test(${in1},${out1});”,//stored procedure invocation
     *     “preStatements”:[],//default []
     *     “postStatements”:[],//default []
     *     “displayRows”:10,//default 10
     *     “datasources”:{
     *         “type”:”MYSQL”,//database type
     *         “host”:””,//ip
     *         “port”:1521,//port
     *         “userName”:””,//username
     *         “password”:””,//password
     *         “database”:””,//database name
     *         “connectType”:”ORACLE_SERVICE_NAME”//default “ORACLE_SERVICE_NAME”, only Oracle needs: ORACLE_SERVICE_NAME: service name, ORACLE_SID: SID
     *         “other”:{
     *             “schema”:”xxx”//schema name, only effective for Oracle 12g and above
     *         }//other parameters, optional
     *     }
     * }
     *
     * taskParams SPARK (SparkSQL development)
     * {
     *     "localParams": [],//default []
     *     "rawScript": "script",//script content
     *     "resourceList": [],//default []
     *     "programType": "SQL",//default "SQL"
     *     "mainClass": "",//default ""
     *     "deployMode": "client",//default "client"
     *     "yarnQueue":"",//default ""
     *     "master": "",//default ""
     *     "driverCores": 1,//default 1
     *     "driverMemory": "512M",//default "512M"
     *     "numExecutors": 1,//default 1
     *     "executorMemory": "1G",//default 1G
     *     "executorCores": 1,//default 1
     *     "sqlExecutionType": "SCRIPT"//default "SCRIPT"
     * }
     *
     * taskParams SUB_PROCESS (sub-task, development tasks also use this)
     * {
     *     "localParams": [],//default []
     *     "resourceList": [],//default []
     *     "processDefinitionCode": 135576103357024//sub-task code
     * }
     */
    private String taskDefinitionJson;

    /**
     * Node relation JSON string (required)
     * Format as follows
     * [{
     * "id":1,//only present when updating
     * "preTaskCode":0,
     * "preTaskVersion":0,
     * "postTaskCode":133455210749664,
     * "postTaskVersion":10,
     * "conditionType":"NONE"//default "NONE"
     * }]
     */
    private String taskRelationJson;

    /**
     * Node coordinate info string (required)
     * Format as follows
     * [{"taskCode":node code,"x":225,"y":302}]
     */
    private String locations;

}
