-- 字典类型新增
SET IDENTITY_INSERT "SYSTEM_DICT_TYPE" ON;
INSERT INTO "SYSTEM_DICT_TYPE"
(DICT_ID, DICT_NAME, DICT_TYPE, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(111, '表类型', 'table_type', '0', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_TYPE"
(DICT_ID, DICT_NAME, DICT_TYPE, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(112, '表名-大小写', 'table_name_case', '0', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_TYPE"
(DICT_ID, DICT_NAME, DICT_TYPE, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(113, '元数据审核状态', 'meta_audit_status', '0', 'admin', '2026-04-23 09:52:37.000', NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_TYPE"
(DICT_ID, DICT_NAME, DICT_TYPE, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(114, '元数据任务状态', 'meta_task_status', '0', 'admin', '2026-04-21 10:23:23.000', NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_TYPE"
(DICT_ID, DICT_NAME, DICT_TYPE, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(115, '是否主表', 'table_yes_no', '0', 'admin', '2026-04-21 10:23:01.000', NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_TYPE"
(DICT_ID, DICT_NAME, DICT_TYPE, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(116, '元数据采集方式', 'mc_collect_mode', '0', 'admin', '2026-04-21 10:08:10.000', NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_TYPE"
(DICT_ID, DICT_NAME, DICT_TYPE, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(117, '采集范围', 'mc_collect_scope', '0', 'admin', '2026-04-21 10:07:04.000', NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_TYPE"
(DICT_ID, DICT_NAME, DICT_TYPE, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES (118,'采集任务实例状态','mc_task_instance_status','0','admin','2026-04-21 10:07:21.000',null,null,null);
SET IDENTITY_INSERT "SYSTEM_DICT_TYPE" OFF;


-- 字典值新增
SET IDENTITY_INSERT "SYSTEM_DICT_DATA" ON;
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(421, 6, '报表应用', '6', 'sys_source_system_type', NULL, 'primary', 'N', '0', 'admin', '2026-04-29 16:45:18.000', NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(422, 5, '数据服务（API）', '5', 'sys_source_system_type', NULL, 'primary', 'N', '0', 'admin', '2026-04-29 16:45:04.000', NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(423, 4, '数据应用层', '4', 'sys_source_system_type', NULL, 'primary', 'N', '0', 'admin', '2026-04-29 16:44:37.000', NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(424, 3, '数据加工层', '3', 'sys_source_system_type', NULL, 'primary', 'N', '0', 'admin', '2026-04-29 16:44:12.000', 'admin', '2026-04-29 16:44:24.000', NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(426, 2, '数据采集层', '2', 'sys_source_system_type', NULL, 'primary', 'N', '0', 'admin', '2026-04-29 16:44:12.000', 'admin', '2026-04-29 16:44:24.000', NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(427, 1, '业务系统', '1', 'sys_source_system_type', NULL, 'primary', 'N', '0', 'admin', '2026-04-29 16:44:12.000', 'admin', '2026-04-29 16:44:24.000', NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(425, 0, '应用表', '4', 'table_type', NULL, NULL, 'N', '0', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(454, 0, '维度表', '3', 'table_type', NULL, NULL, 'N', '0', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(453, 0, '汇总表', '2', 'table_type', NULL, NULL, 'N', '0', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(452, 0, '明细表', '1', 'table_type', NULL, NULL, 'N', '0', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(451, 0, '小写', '2', 'table_name_case', NULL, NULL, 'N', '0', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(450, 0, '大写', '1', 'table_name_case', NULL, NULL, 'N', '0', NULL, NULL, NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(449, 0, '审批异常', '5', 'meta_audit_status', NULL, 'warning', 'N', '0', 'admin', '2026-04-23 09:54:12.000', NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(448, 0, '审批撤回', '4', 'meta_audit_status', NULL, 'info', 'N', '0', 'admin', '2026-04-23 09:53:53.000', NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(447, 0, '审批拒绝', '3', 'meta_audit_status', NULL, 'danger', 'N', '0', 'admin', '2026-04-23 09:53:22.000', NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(446, 0, '审批通过', '2', 'meta_audit_status', NULL, 'success', 'N', '0', 'admin', '2026-04-23 09:53:04.000', NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(445, 0, '审批中', '1', 'meta_audit_status', NULL, 'primary', 'N', '0', 'admin', '2026-04-23 09:52:53.000', NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(444, 0, '已发布', '1', 'meta_task_status', NULL, 'success', 'N', '0', 'admin', '2026-04-21 10:25:37.000', NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(443, 0, '未发布', '0', 'meta_task_status', NULL, 'danger', 'N', '0', 'admin', '2026-04-21 10:25:12.000', 'admin', '2026-04-21 10:25:23.000', NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(442, 0, '否', '0', 'table_yes_no', NULL, 'danger', 'N', '0', 'admin', '2026-04-21 10:24:30.000', 'admin', '2026-04-21 10:24:36.000', NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(441, 0, '是', '1', 'table_yes_no', NULL, 'primary', 'N', '0', 'admin', '2026-04-21 10:24:18.000', NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(440, 0, 'CDC捕获', '3', 'mc_collect_mode', NULL, 'primary', 'N', '0', 'admin', '2026-04-21 10:08:56.000', 'admin', '2026-04-21 10:09:04.000', NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(439, 0, '全量', '2', 'mc_collect_mode', NULL, 'primary', 'N', '0', 'admin', '2026-04-21 10:08:45.000', NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(438, 0, '增量', '1', 'mc_collect_mode', NULL, 'primary', 'N', '0', 'admin', '2026-04-21 10:08:28.000', NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(437, 1, '自定义库', '1', 'mc_collect_scope', NULL, 'default', 'N', '0', 'admin', '2026-04-21 10:07:31.000', NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES(436, 0, '整个数据源', '2', 'mc_collect_scope', NULL, 'default', 'N', '0', 'admin', '2026-04-21 10:07:21.000', NULL, NULL, NULL);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES (456,1,'正在执行','1','mc_task_instance_status',null,'primary','N','0','admin','2026-04-21 10:07:21.000',null,null,null);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES (457,2,'失败','2','mc_task_instance_status',null,'danger','N','0','admin','2026-04-21 10:07:21.000',null,null,null);
INSERT INTO "SYSTEM_DICT_DATA"
(DICT_CODE, DICT_SORT, DICT_LABEL, DICT_VALUE, DICT_TYPE, CSS_CLASS, LIST_CLASS, IS_DEFAULT, STATUS, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK)
VALUES (458,9,'成功','9','mc_task_instance_status',null,'success','N','0','admin','2026-04-21 10:07:21.000',null,null,null);
SET IDENTITY_INSERT "SYSTEM_DICT_DATA" OFF;

SET IDENTITY_INSERT "SYSTEM_MENU" ON;
INSERT INTO "SYSTEM_MENU" ("MENU_ID","MENU_NAME","PARENT_ID","ORDER_NUM","PATH","COMPONENT","QUERY","IS_FRAME","IS_CACHE","ROUTE_NAME","MENU_TYPE","VISIBLE","STATUS","PERMS","ICON","CREATE_BY","CREATE_TIME","UPDATE_BY","UPDATE_TIME","REMARK" ) VALUES (2738,'来源系统',2375,2,'sourceSystem','att/sourceSystem/index',null,1,0,null,'C','0','0','att:sourcesystem:list','box-3-line','admin',to_timestamp('2026-04-03 10:32:23','SYYYY-MM-DD HH24:MI:SS.FF6'),'admin',to_timestamp('2026-04-24 11:14:18','SYYYY-MM-DD HH24:MI:SS.FF6'),'来源系统菜单');
INSERT INTO "SYSTEM_MENU" ("MENU_ID","MENU_NAME","PARENT_ID","ORDER_NUM","PATH","COMPONENT","QUERY","IS_FRAME","IS_CACHE","ROUTE_NAME","MENU_TYPE","VISIBLE","STATUS","PERMS","ICON","CREATE_BY","CREATE_TIME","UPDATE_BY","UPDATE_TIME","REMARK" ) VALUES (2739,'来源系统查询',2738,1,'#',null,null,1,0,null,'F','0','0','att:sourcesystem:query','#','admin',to_timestamp('2026-04-03 10:35:46','SYYYY-MM-DD HH24:MI:SS.FF6'),'admin',to_timestamp('2026-04-15 15:09:24','SYYYY-MM-DD HH24:MI:SS.FF6'),null);
INSERT INTO "SYSTEM_MENU" ("MENU_ID","MENU_NAME","PARENT_ID","ORDER_NUM","PATH","COMPONENT","QUERY","IS_FRAME","IS_CACHE","ROUTE_NAME","MENU_TYPE","VISIBLE","STATUS","PERMS","ICON","CREATE_BY","CREATE_TIME","UPDATE_BY","UPDATE_TIME","REMARK" ) VALUES (2740,'来源系统新增',2738,2,'#',null,null,1,0,null,'F','0','0','att:sourcesystem:add','#','admin',to_timestamp('2026-04-03 10:35:49','SYYYY-MM-DD HH24:MI:SS.FF6'),'admin',to_timestamp('2026-04-15 15:09:46','SYYYY-MM-DD HH24:MI:SS.FF6'),null);
INSERT INTO "SYSTEM_MENU" ("MENU_ID","MENU_NAME","PARENT_ID","ORDER_NUM","PATH","COMPONENT","QUERY","IS_FRAME","IS_CACHE","ROUTE_NAME","MENU_TYPE","VISIBLE","STATUS","PERMS","ICON","CREATE_BY","CREATE_TIME","UPDATE_BY","UPDATE_TIME","REMARK" ) VALUES (2741,'来源系统修改',2738,3,'#',null,null,1,0,null,'F','0','0','att:sourcesystem:edit','#','admin',to_timestamp('2026-04-03 10:35:52','SYYYY-MM-DD HH24:MI:SS.FF6'),'admin',to_timestamp('2026-04-15 15:16:53','SYYYY-MM-DD HH24:MI:SS.FF6'),null);
INSERT INTO "SYSTEM_MENU" ("MENU_ID","MENU_NAME","PARENT_ID","ORDER_NUM","PATH","COMPONENT","QUERY","IS_FRAME","IS_CACHE","ROUTE_NAME","MENU_TYPE","VISIBLE","STATUS","PERMS","ICON","CREATE_BY","CREATE_TIME","UPDATE_BY","UPDATE_TIME","REMARK" ) VALUES (2742,'来源系统删除',2738,4,'#',null,null,1,0,null,'F','0','0','att:sourcesystem:remove','#','admin',to_timestamp('2026-04-03 10:35:56','SYYYY-MM-DD HH24:MI:SS.FF6'),'admin',to_timestamp('2026-04-15 15:16:45','SYYYY-MM-DD HH24:MI:SS.FF6'),null);
INSERT INTO "SYSTEM_MENU" ("MENU_ID","MENU_NAME","PARENT_ID","ORDER_NUM","PATH","COMPONENT","QUERY","IS_FRAME","IS_CACHE","ROUTE_NAME","MENU_TYPE","VISIBLE","STATUS","PERMS","ICON","CREATE_BY","CREATE_TIME","UPDATE_BY","UPDATE_TIME","REMARK" ) VALUES (2743,'来源系统导出',2738,5,'#',null,null,1,0,null,'F','0','0','att:sourcesystem:export','#','admin',to_timestamp('2026-04-03 10:36:08','SYYYY-MM-DD HH24:MI:SS.FF6'),'admin',to_timestamp('2026-04-15 15:16:29','SYYYY-MM-DD HH24:MI:SS.FF6'),null);
INSERT INTO "SYSTEM_MENU" ("MENU_ID","MENU_NAME","PARENT_ID","ORDER_NUM","PATH","COMPONENT","QUERY","IS_FRAME","IS_CACHE","ROUTE_NAME","MENU_TYPE","VISIBLE","STATUS","PERMS","ICON","CREATE_BY","CREATE_TIME","UPDATE_BY","UPDATE_TIME","REMARK" ) VALUES (2744,'来源系统导入',2738,6,'#',null,null,1,0,null,'F','0','0','att:sourcesystem:import','#','admin',to_timestamp('2026-04-03 10:36:14','SYYYY-MM-DD HH24:MI:SS.FF6'),'admin',to_timestamp('2026-04-15 15:16:40','SYYYY-MM-DD HH24:MI:SS.FF6'),null);
INSERT INTO "SYSTEM_MENU" ("MENU_ID","MENU_NAME","PARENT_ID","ORDER_NUM","PATH","COMPONENT","QUERY","IS_FRAME","IS_CACHE","ROUTE_NAME","MENU_TYPE","VISIBLE","STATUS","PERMS","ICON","CREATE_BY","CREATE_TIME","UPDATE_BY","UPDATE_TIME","REMARK" ) VALUES (2745,'最新元数据查询',2727,1,'#',null,null,1,0,null,'F','0','0','mc:metadata:table:query','#','admin',to_timestamp('2025-12-18 11:05:20','SYYYY-MM-DD HH24:MI:SS.FF6'),'admin',to_timestamp('2026-04-27 11:24:44','SYYYY-MM-DD HH24:MI:SS.FF6'),null);
INSERT INTO "SYSTEM_MENU" ("MENU_ID","MENU_NAME","PARENT_ID","ORDER_NUM","PATH","COMPONENT","QUERY","IS_FRAME","IS_CACHE","ROUTE_NAME","MENU_TYPE","VISIBLE","STATUS","PERMS","ICON","CREATE_BY","CREATE_TIME","UPDATE_BY","UPDATE_TIME","REMARK" ) VALUES (2746,'最新元数据新增',2727,2,'#',null,null,1,0,null,'F','0','0','mc:metadata:table:add','#','admin',to_timestamp('2025-12-18 11:05:20','SYYYY-MM-DD HH24:MI:SS.FF6'),'admin',to_timestamp('2026-04-27 11:25:04','SYYYY-MM-DD HH24:MI:SS.FF6'),null);
INSERT INTO "SYSTEM_MENU" ("MENU_ID","MENU_NAME","PARENT_ID","ORDER_NUM","PATH","COMPONENT","QUERY","IS_FRAME","IS_CACHE","ROUTE_NAME","MENU_TYPE","VISIBLE","STATUS","PERMS","ICON","CREATE_BY","CREATE_TIME","UPDATE_BY","UPDATE_TIME","REMARK" ) VALUES (2747,'最新元数据修改',2727,3,'#',null,null,1,0,null,'F','0','0','mc:metadata:table:edit','#','admin',to_timestamp('2025-12-18 11:05:20','SYYYY-MM-DD HH24:MI:SS.FF6'),'admin',to_timestamp('2026-04-27 11:25:12','SYYYY-MM-DD HH24:MI:SS.FF6'),null);
INSERT INTO "SYSTEM_MENU" ("MENU_ID","MENU_NAME","PARENT_ID","ORDER_NUM","PATH","COMPONENT","QUERY","IS_FRAME","IS_CACHE","ROUTE_NAME","MENU_TYPE","VISIBLE","STATUS","PERMS","ICON","CREATE_BY","CREATE_TIME","UPDATE_BY","UPDATE_TIME","REMARK" ) VALUES (2748,'最新元数据删除',2727,4,'#',null,null,1,0,null,'F','0','0','mc:metadata:table:remove','#','admin',to_timestamp('2025-12-18 11:05:21','SYYYY-MM-DD HH24:MI:SS.FF6'),'admin',to_timestamp('2026-04-27 11:25:19','SYYYY-MM-DD HH24:MI:SS.FF6'),null);
INSERT INTO "SYSTEM_MENU" ("MENU_ID","MENU_NAME","PARENT_ID","ORDER_NUM","PATH","COMPONENT","QUERY","IS_FRAME","IS_CACHE","ROUTE_NAME","MENU_TYPE","VISIBLE","STATUS","PERMS","ICON","CREATE_BY","CREATE_TIME","UPDATE_BY","UPDATE_TIME","REMARK" ) VALUES (2749,'最新元数据详情',2727,5,'#',null,null,1,0,null,'F','0','0','mc:metadata:table:detail','#','admin',to_timestamp('2025-12-18 11:05:21','SYYYY-MM-DD HH24:MI:SS.FF6'),'admin',to_timestamp('2026-04-27 11:25:26','SYYYY-MM-DD HH24:MI:SS.FF6'),null);
SET IDENTITY_INSERT "SYSTEM_MENU" OFF;

UPDATE "SYSTEM_MENU" SET "MENU_NAME" = '元数据管理',"PARENT_ID" = 2723,"ORDER_NUM" = 1,"PATH" = 'meta',"COMPONENT" = null,"QUERY" = null,"IS_FRAME" = 1,"IS_CACHE" = 0,"ROUTE_NAME" = null,"MENU_TYPE" = 'M',"VISIBLE" = '0',"STATUS" = '0',"PERMS" = null,"ICON" = 'ysjgl',"CREATE_BY" = 'admin',"CREATE_TIME" = to_timestamp('2026-03-25 17:42:50','SYYYY-MM-DD HH24:MI:SS.FF6'),"UPDATE_BY" = 'admin',"UPDATE_TIME" = to_timestamp('2026-03-27 16:10:44','SYYYY-MM-DD HH24:MI:SS.FF6'),"REMARK" = null WHERE "MENU_ID" = 2724;
UPDATE "SYSTEM_MENU" SET "MENU_NAME" = '采集任务',"PARENT_ID" = 2724,"ORDER_NUM" = 1,"PATH" = 'task',"COMPONENT" = 'mc/task/structured/index',"QUERY" = null,"IS_FRAME" = 1,"IS_CACHE" = 0,"ROUTE_NAME" = null,"MENU_TYPE" = 'C',"VISIBLE" = '0',"STATUS" = '0',"PERMS" = null,"ICON" = '#',"CREATE_BY" = 'admin',"CREATE_TIME" = to_timestamp('2026-03-25 17:43:26','SYYYY-MM-DD HH24:MI:SS.FF6'),"UPDATE_BY" = 'admin',"UPDATE_TIME" = to_timestamp('2026-05-07 11:47:58','SYYYY-MM-DD HH24:MI:SS.FF6'),"REMARK" = null WHERE "MENU_ID" = 2725;
UPDATE "SYSTEM_MENU" SET "MENU_NAME" = '采集实例',"PARENT_ID" = 2724,"ORDER_NUM" = 2,"PATH" = 'instance',"COMPONENT" = 'mc/instance/structured/index',"QUERY" = null,"IS_FRAME" = 1,"IS_CACHE" = 0,"ROUTE_NAME" = null,"MENU_TYPE" = 'C',"VISIBLE" = '0',"STATUS" = '0',"PERMS" = null,"ICON" = '#',"CREATE_BY" = 'admin',"CREATE_TIME" = to_timestamp('2026-03-25 17:44:36','SYYYY-MM-DD HH24:MI:SS.FF6'),"UPDATE_BY" = 'admin',"UPDATE_TIME" = to_timestamp('2026-05-07 11:48:22','SYYYY-MM-DD HH24:MI:SS.FF6'),"REMARK" = null WHERE "MENU_ID" = 2726;
UPDATE "SYSTEM_MENU" SET "MENU_NAME" = '最新元数据',"PARENT_ID" = 2724,"ORDER_NUM" = 3,"PATH" = 'management',"COMPONENT" = 'meta/unreleased/structured/table/index',"QUERY" = null,"IS_FRAME" = 1,"IS_CACHE" = 0,"ROUTE_NAME" = null,"MENU_TYPE" = 'C',"VISIBLE" = '0',"STATUS" = '0',"PERMS" = 'mc:metadata:table:list',"ICON" = '#',"CREATE_BY" = 'admin',"CREATE_TIME" = '2026-03-25 17:44:52',"UPDATE_BY" = 'admin',"UPDATE_TIME" = '2026-05-12 14:57:16',"REMARK" = null WHERE "MENU_ID" = 2727;
UPDATE "SYSTEM_MENU" SET "MENU_NAME" = '定版元数据',"PARENT_ID" = 2724,"ORDER_NUM" = 4,"PATH" = 'comparison',"COMPONENT" = 'meta/released/structured/table/index',"QUERY" = null,"IS_FRAME" = 1,"IS_CACHE" = 0,"ROUTE_NAME" = null,"MENU_TYPE" = 'C',"VISIBLE" = '0',"STATUS" = '0',"PERMS" = null,"ICON" = '#',"CREATE_BY" = 'admin',"CREATE_TIME" = to_timestamp('2026-03-25 17:45:07','SYYYY-MM-DD HH24:MI:SS.FF6'),"UPDATE_BY" = 'admin',"UPDATE_TIME" = to_timestamp('2026-05-07 11:49:05','SYYYY-MM-DD HH24:MI:SS.FF6'),"REMARK" = null WHERE "MENU_ID" = 2728;
UPDATE "SYSTEM_MENU" SET "MENU_NAME" = '元数据比对',"PARENT_ID" = 2724,"ORDER_NUM" = 5,"PATH" = 'comparison',"COMPONENT" = 'sys/developing/index',"QUERY" = null,"IS_FRAME" = 1,"IS_CACHE" = 0,"ROUTE_NAME" = null,"MENU_TYPE" = 'C',"VISIBLE" = '1',"STATUS" = '1',"PERMS" = '',"ICON" = '#',"CREATE_BY" = 'admin',"CREATE_TIME" = '2026-03-25 17:45:35',"UPDATE_BY" = 'admin',"UPDATE_TIME" = '2026-05-12 14:50:21',"REMARK" = null WHERE "MENU_ID" = 2729;
