-- 菜单数据新增
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2750,'业务分类',2694,2,'businessCategory','dm/businessCategory/index',null,1,0,null,'C','0','0','dm:businesscategory:list','ywfc','admin','2026-03-30 16:46:41','admin','2026-04-15 15:06:14',null);
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2751,'业务分类查询',2750,1,'#',null,null,1,0,null,'F','0','0','dm:businesscategory:query','#','admin','2026-04-08 11:51:41',null,null,null);
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2752,'业务分类新增',2750,2,'#',null,null,1,0,null,'F','0','0','dm:businesscategory:add','#','admin','2026-04-08 11:51:49',null,null,null);
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2753,'业务分类修改',2750,3,'#',null,null,1,0,null,'F','0','0','dm:businesscategory:edit','#','admin','2026-04-08 11:51:56',null,null,null);
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2754,'业务分类删除',2750,4,'#',null,null,1,0,null,'F','0','0','dm:businesscategory:remove','#','admin','2026-04-08 11:52:16',null,null,null);
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2755,'业务分类导出',2750,5,'#',null,null,1,0,null,'F','0','0','dm:businesscategory:export','#','admin','2026-04-08 11:52:24',null,null,null);
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2756,'业务分类导入',2750,6,'#',null,null,1,0,null,'F','0','0','dm:businesscategory:import','#','admin','2026-04-08 11:52:32',null,null,null);
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2757,'标签类目管理导出',2763,5,'#',null,null,1,0,null,'F','0','0','att:tagCat:export','#','吴同','2025-07-14 10:16:37','wutong','2025-09-24 17:38:35','');
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2758,'标签类目管理删除',2763,4,'#',null,null,1,0,null,'F','0','0','att:tagCat:remove','#','吴同','2025-07-14 10:16:35','wutong','2025-09-24 17:38:29','');
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2759,'标签类目管理修改',2763,3,'#',null,null,1,0,null,'F','0','0','att:tagCat:edit','#','吴同','2025-07-14 10:16:29','wutong','2025-09-24 17:38:22','');
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2760,'标签类目管理新增',2763,2,'#',null,null,1,0,null,'F','0','0','att:tagCat:add','#','吴同','2025-07-14 10:16:27','wutong','2025-09-24 17:38:15','');
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2761,'标签类目管理查询',2763,1,'#',null,null,1,0,null,'F','0','0','att:tagCat:query','#','吴同','2025-07-14 10:16:18','wutong','2025-09-24 17:38:07','');
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2762,'标签类目管理导入',2763,6,'#',null,null,1,0,null,'F','0','0','att:tagCat:import','#','吴同','2025-07-14 10:15:47','wutong','2025-09-24 17:38:44','');
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2763,'标签类目管理',2352,9,'tagCat','att/cat/tagCat/index',null,1,0,null,'C','0','0','att:tagCat:list','#','吴同','2025-07-14 10:14:52','admin','2026-03-30 17:37:12','标签类目管理菜单');
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2764,'标签管理导入',2770,6,'#',null,null,1,0,null,'F','0','0','att:tag:import','#','吴同','2025-07-14 10:18:37','wutong','2025-09-24 16:33:35','');
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2765,'标签管理导出',2770,5,'#',null,null,1,0,null,'F','0','0','att:tag:export','#','吴同','2025-07-14 10:18:37','wutong','2025-09-24 16:33:29','');
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2766,'标签管理删除',2770,4,'#',null,null,1,0,null,'F','0','0','att:tag:remove','#','吴同','2025-07-14 10:18:37','wutong','2025-09-24 16:33:13','');
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2767,'标签管理修改',2770,3,'#',null,null,1,0,null,'F','0','0','att:tag:edit','#','吴同','2025-07-14 10:18:37','wutong','2025-09-24 16:33:06','');
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2768,'标签管理新增',2770,2,'#',null,null,1,0,null,'F','0','0','att:tag:add','#','吴同','2025-07-14 10:18:37','wutong','2025-09-24 16:32:47','');
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2769,'标签管理查询',2770,1,'#',null,null,1,0,null,'F','0','0','att:tag:query','#','吴同','2025-07-14 10:18:37','wutong','2025-09-24 16:32:58','');
INSERT INTO `system_menu` (`menu_id`,`menu_name`,`parent_id`,`order_num`,`path`,`component`,`query`,`is_frame`,`is_cache`,`route_name`,`menu_type`,`visible`,`status`,`perms`,`icon`,`create_by`,`create_time`,`update_by`,`update_time`,`remark` ) VALUES (2770,'资产标签',2314,3,'tag','att/tag/index',null,1,0,null,'C','0','0','att:tag:list','bzsjy','吴同','2025-07-14 10:18:14','admin','2026-03-30 17:21:17','标签管理菜单');
UPDATE `system_menu` SET `order_num` = 8 WHERE `menu_id` = 2674;
UPDATE `system_menu` SET `path` = 'materializedModel',`component` = 'dp/materializedModel/index',`perms` = 'dp:releaseModel:list' WHERE `menu_id` = 2731;
DELETE FROM `system_menu` WHERE `menu_id` = 2709;

-- 字典数据更新
UPDATE `system_dict_data` SET `dict_sort` = 4,`remark` = '直接用于大屏或报表展示的最终数据，如"防汛大屏综合指标表"。' WHERE `dict_code` = 425;
UPDATE `system_dict_data` SET `dict_sort` = 3,`remark` = '按条件统计出来的阶段性结果，如"测站日降水量表"、"月均水位表"。' WHERE `dict_code` = 454;
UPDATE `system_dict_data` SET `dict_sort` = 2,`remark` = '记录未经加工的原始流水记录，如"单次水位上报"、"设备报警日志"。' WHERE `dict_code` = 453;
UPDATE `system_dict_data` SET `dict_sort` = 1,`remark` = '存放固定的基础档案信息，如"测站基本属性表"、"水库名录"等。' WHERE `dict_code` = 452;
