<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>tech.qiantong</groupId>
        <artifactId>qdata-module-ai</artifactId>
        <version>${qdata.version}</version>
    </parent>

    <artifactId>qdata-module-ai-biz</artifactId>

    <description>
        qdata-module-ai-biz module
    </description>
    <dependencies>
        <!-- Core module config-->
        <dependency>
            <groupId>tech.qiantong</groupId>
            <artifactId>qdata-config</artifactId>
            <version>${qdata.version}</version>
        </dependency>

        <!-- System module websocket-->
        <dependency>
            <groupId>tech.qiantong</groupId>
            <artifactId>qdata-websocket</artifactId>
            <version>${qdata.version}</version>
        </dependency>

        <!-- System module qdata-security -->
        <dependency>
            <groupId>tech.qiantong</groupId>
            <artifactId>qdata-security</artifactId>
            <version>${qdata.version}</version>
        </dependency>

        <!-- System module mybatis -->
        <dependency>
            <groupId>tech.qiantong</groupId>
            <artifactId>qdata-mybatis</artifactId>
            <version>${qdata.version}</version>
        </dependency>

        <!-- System module redis -->
        <dependency>
            <groupId>tech.qiantong</groupId>
            <artifactId>qdata-redis</artifactId>
            <version>${qdata.version}</version>
        </dependency>

        <!-- File upload-->
        <dependency>
            <groupId>tech.qiantong</groupId>
            <artifactId>qdata-file</artifactId>
            <version>${qdata.version}</version>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>tech.qiantong</groupId>
            <artifactId>qdata-module-system-api</artifactId>
            <version>${qdata.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>tech.qiantong</groupId>
            <artifactId>qdata-module-ai-api</artifactId>
            <version>${qdata.version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>
</project>
