/*
 * Copyright © 2025-present Jiangsu Qiantong Technology Co., Ltd.
 *
 * This file is part of qData Data Middle Platform (Open Source Edition).
 *
 * qData is licensed under Apache License 2.0 with additional qData terms.
 * You may use qData for commercial purposes, but you may not remove, hide,
 * modify, or replace the qData logo, copyright notices, license notices,
 * or attribution information without a separate commercial license.
 *
 * White-label use, OEM distribution, rebranding, or presenting qData as
 * another product requires separate commercial authorization from
 * Jiangsu Qiantong Technology Co., Ltd.
 *
 * Business License: https://community.qdata.tech/business/policy.html
 * See the LICENSE file in the project root for full license information.
 */

package tech.qiantong.qdata.quality.dal.dataobject.asset;

import com.baomidou.mybatisplus.annotation.*;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;
import tech.qiantong.qdata.common.core.domain.BaseEntity;

import java.util.List;

/**
 * Data Asset DO Object DA_ASSET
 *
 * @author lhs
 * @date 2025-01-21
 */
@Data
@TableName(value = "DA_ASSET")
// Primary key auto-increment for Oracle, PostgreSQL, Kingbase, DB2, H2 databases. If it is a database such as MySQL, you do not need to write it.
// @KeySequence("DA_ASSET_seq")
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
public class DaAssetDO extends BaseEntity {
    @TableField(exist = false)
    private static final long serialVersionUID = 1L;

    /** ID */
    @TableId(type = IdType.AUTO)
    private Long id;

    /** Asset name */
    private String name;

    @Schema(description = "资产类型", example = "")
    private String type;

    /** Category code */
    private String catCode;

    @TableField(exist = false)
    private String catName;

    /**Is it an applied-for asset or an asset generated by the project itself? 0: Application, 1: Self-created */
    @TableField(exist = false)
    private String sourceType;

    /** Data connection id */
    private Long datasourceId;

    @TableField(exist = false)
    private String datasourceName;

    @TableField(exist = false)
    private String datasourceIp;

    @TableField(exist = false)
    private String datasourceType;

    /** table name */
    private String tableName;

    /** Table description */
    private String tableComment;

    /** Data volume */
    private Long dataCount;

    /** Field amount */
    private Long fieldCount;

    /** Source; 1: data discovery; 2: data model; */
    private String source;

    /** status */
    private String status;

    /** Description */
    private String description;

    /** Is it valid */
    private Boolean validFlag;

    /** Delete flag */
    @TableLogic
    private Boolean delFlag;

    @Schema(description = "项目id", example = "")
    @TableField(exist = false)
    private Long projectId;

    @Schema(description = "项目编码", example = "")
    @TableField(exist = false)
    private String projectCode;
    /** Create type */
    private String createType;
}
