CREATE TABLE "QDATA"."AI_CHAT_CONVERSATION"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "USER_ID" BIGINT NOT NULL,
 "TITLE" VARCHAR2(128) NOT NULL,
 "PINNED" VARCHAR2(1) DEFAULT '0'
 NOT NULL,
 "PINNED_TIME" DATETIME(6) NULL,
 "DATASOURCE_ID" BIGINT NOT NULL,
 "FACT_TABLE_NAME" VARCHAR2(256) NOT NULL,
 "FACT_TABLE_COMMENT" VARCHAR2(2000) NULL,
 "DIMENSION_TABLE" TEXT NULL,
 "ASSOCIATIONS" TEXT NULL,
 "JOIN_CONDITION_MATCH_FLAG" VARCHAR2(1) DEFAULT '0'
 NULL,
 "JOIN_CONDITION_MATCH_TYPE" CHAR(1) DEFAULT '1'
 NULL,
 "VALID_FLAG" VARCHAR2(1) DEFAULT '1'
 NOT NULL,
 "DEL_FLAG" VARCHAR2(1) DEFAULT '0'
 NOT NULL,
 "CREATE_BY" VARCHAR2(32) NULL,
 "CREATOR_ID" BIGINT NULL,
 "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP
 NOT NULL,
 "UPDATE_BY" VARCHAR2(32) NULL,
 "UPDATER_ID" BIGINT NULL,
 "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP
 NOT NULL,
 "REMARK" VARCHAR2(512) NULL,
 "DATASOURCE_TYPE" VARCHAR(32) NULL
);

CREATE TABLE "QDATA"."AI_CHAT_MESSAGE"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "CONVERSATION_ID" BIGINT NOT NULL,
 "REPLY_ID" BIGINT NULL,
 "REPLY_TYPE" VARCHAR2(8188) NULL,
 "USER_ID" BIGINT NOT NULL,
 "TYPE" VARCHAR2(10) DEFAULT '1'
 NULL,
 "CONTENT" TEXT NULL,
 "CONTEXT_FLAG" VARCHAR2(1) DEFAULT '1'
 NOT NULL,
 "VALID_FLAG" VARCHAR2(1) DEFAULT '1'
 NOT NULL,
 "DEL_FLAG" VARCHAR2(1) DEFAULT '0'
 NOT NULL,
 "CREATE_BY" VARCHAR2(32) NULL,
 "CREATOR_ID" BIGINT NULL,
 "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP
 NOT NULL,
 "UPDATE_BY" VARCHAR2(32) NULL,
 "UPDATER_ID" BIGINT NULL,
 "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP
 NOT NULL,
 "REMARK" VARCHAR2(512) NULL
);

CREATE TABLE "QDATA"."AI_MODEL"
(
 "ID" BIGINT IDENTITY(1,1) NOT NULL,
 "NAME" VARCHAR2(32) NOT NULL,
 "PLATFORM" VARCHAR2(10) NOT NULL,
 "API_URL" VARCHAR2(512) NULL,
 "API_KEY" VARCHAR2(256) NULL,
 "SORT_ORDER" INTEGER NOT NULL,
 "DESCRIPTION" VARCHAR2(512) NULL,
 "VALID_FLAG" VARCHAR2(1) DEFAULT '1'
 NOT NULL,
 "DEL_FLAG" VARCHAR2(1) DEFAULT '0'
 NOT NULL,
 "CREATE_BY" VARCHAR2(32) NULL,
 "CREATOR_ID" BIGINT NULL,
 "CREATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP
 NOT NULL,
 "UPDATE_BY" VARCHAR2(32) NULL,
 "UPDATER_ID" BIGINT NULL,
 "UPDATE_TIME" DATETIME(6) DEFAULT CURRENT_TIMESTAMP
 NOT NULL,
 "REMARK" VARCHAR2(512) NULL
);


ALTER TABLE "QDATA"."AI_CHAT_CONVERSATION" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("ID") ;

ALTER TABLE "QDATA"."AI_CHAT_MESSAGE" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("ID") ;

ALTER TABLE "QDATA"."AI_MODEL" ADD CONSTRAINT  NOT CLUSTER  PRIMARY KEY("ID") ;

COMMENT ON TABLE "QDATA"."AI_CHAT_CONVERSATION" IS 'ai聊天对话表';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."ASSOCIATIONS" IS '关联信息;格式 [{"dimensionTable": "维度表名","factColumnName": "事实表外键字段名","dimensionColumnName": "维度表主键字段名","matchReason": "匹配依据"}]';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."CREATE_BY" IS '创建人';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."CREATOR_ID" IS '创建人id';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."DATASOURCE_ID" IS '数据源id';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."DATASOURCE_TYPE" IS '数据源类型';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."DIMENSION_TABLE" IS '维度表;格式 [{"tableName":"表名","tableComment":"表注释"}]';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."FACT_TABLE_COMMENT" IS '事实表注释/事实表描述';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."FACT_TABLE_NAME" IS '事实表名称';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."ID" IS 'ID';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."JOIN_CONDITION_MATCH_FLAG" IS '关联条件匹配状态;0：未匹配，1：已匹配';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."JOIN_CONDITION_MATCH_TYPE" IS '关联条件匹配类型;1：自动匹配 2:手动匹配';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."PINNED" IS '是否置顶;0：不置顶，1：置顶';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."PINNED_TIME" IS '置顶时间';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."REMARK" IS '备注';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."TITLE" IS '对话标题';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."UPDATE_BY" IS '更新人';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."UPDATER_ID" IS '更新人id';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."USER_ID" IS '用户id';

COMMENT ON COLUMN "QDATA"."AI_CHAT_CONVERSATION"."VALID_FLAG" IS '是否有效;0：无效，1：有效';


COMMENT ON TABLE "QDATA"."AI_CHAT_MESSAGE" IS 'ai聊天消息表';

COMMENT ON COLUMN "QDATA"."AI_CHAT_MESSAGE"."CONTENT" IS '消息内容';

COMMENT ON COLUMN "QDATA"."AI_CHAT_MESSAGE"."CONTEXT_FLAG" IS '是否携带上下文;0：否，1：是';

COMMENT ON COLUMN "QDATA"."AI_CHAT_MESSAGE"."CONVERSATION_ID" IS '对话id';

COMMENT ON COLUMN "QDATA"."AI_CHAT_MESSAGE"."CREATE_BY" IS '创建人';

COMMENT ON COLUMN "QDATA"."AI_CHAT_MESSAGE"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "QDATA"."AI_CHAT_MESSAGE"."CREATOR_ID" IS '创建人id';

COMMENT ON COLUMN "QDATA"."AI_CHAT_MESSAGE"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';

COMMENT ON COLUMN "QDATA"."AI_CHAT_MESSAGE"."ID" IS 'ID';

COMMENT ON COLUMN "QDATA"."AI_CHAT_MESSAGE"."REMARK" IS '备注';

COMMENT ON COLUMN "QDATA"."AI_CHAT_MESSAGE"."REPLY_ID" IS '回复id';

COMMENT ON COLUMN "QDATA"."AI_CHAT_MESSAGE"."REPLY_TYPE" IS '回复类型;1:知识问答 2: 知识图表';

COMMENT ON COLUMN "QDATA"."AI_CHAT_MESSAGE"."TYPE" IS '消息类型;1:用户 2：机器人';

COMMENT ON COLUMN "QDATA"."AI_CHAT_MESSAGE"."UPDATE_BY" IS '更新人';

COMMENT ON COLUMN "QDATA"."AI_CHAT_MESSAGE"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "QDATA"."AI_CHAT_MESSAGE"."UPDATER_ID" IS '更新人id';

COMMENT ON COLUMN "QDATA"."AI_CHAT_MESSAGE"."USER_ID" IS '用户id';

COMMENT ON COLUMN "QDATA"."AI_CHAT_MESSAGE"."VALID_FLAG" IS '是否有效;0：无效，1：有效';

COMMENT ON TABLE "QDATA"."AI_MODEL" IS '模型管理';

COMMENT ON COLUMN "QDATA"."AI_MODEL"."API_KEY" IS 'API秘钥';

COMMENT ON COLUMN "QDATA"."AI_MODEL"."API_URL" IS 'API地址';

COMMENT ON COLUMN "QDATA"."AI_MODEL"."CREATE_BY" IS '创建人';

COMMENT ON COLUMN "QDATA"."AI_MODEL"."CREATE_TIME" IS '创建时间';

COMMENT ON COLUMN "QDATA"."AI_MODEL"."CREATOR_ID" IS '创建人id';

COMMENT ON COLUMN "QDATA"."AI_MODEL"."DEL_FLAG" IS '删除标志;1：已删除，0：未删除';

COMMENT ON COLUMN "QDATA"."AI_MODEL"."DESCRIPTION" IS '描述';

COMMENT ON COLUMN "QDATA"."AI_MODEL"."ID" IS 'ID';

COMMENT ON COLUMN "QDATA"."AI_MODEL"."NAME" IS '模型名称;例如 qwen-max';

COMMENT ON COLUMN "QDATA"."AI_MODEL"."PLATFORM" IS '平台;1:通义千问 2:DeepSeek';

COMMENT ON COLUMN "QDATA"."AI_MODEL"."REMARK" IS '备注';

COMMENT ON COLUMN "QDATA"."AI_MODEL"."SORT_ORDER" IS '排序';

COMMENT ON COLUMN "QDATA"."AI_MODEL"."UPDATE_BY" IS '更新人';

COMMENT ON COLUMN "QDATA"."AI_MODEL"."UPDATE_TIME" IS '更新时间';

COMMENT ON COLUMN "QDATA"."AI_MODEL"."UPDATER_ID" IS '更新人id';

COMMENT ON COLUMN "QDATA"."AI_MODEL"."VALID_FLAG" IS '是否有效;0：无效，1：有效';
