/*
 * Copyright © 2025-present Jiangsu Qiantong Technology Co., Ltd.
 *
 * This file is part of qData Data Middle Platform (Open Source Edition).
 *
 * qData is licensed under Apache License 2.0 with additional qData terms.
 * You may use qData for commercial purposes, but you may not remove, hide,
 * modify, or replace the qData logo, copyright notices, license notices,
 * or attribution information without a separate commercial license.
 *
 * White-label use, OEM distribution, rebranding, or presenting qData as
 * another product requires separate commercial authorization from
 * Jiangsu Qiantong Technology Co., Ltd.
 *
 * Business License: https://community.qdata.tech/business/policy.html
 * See the LICENSE file in the project root for full license information.
 */

package tech.qiantong.qdata.module.da.dal.dataobject.daAssetApply;

import com.baomidou.mybatisplus.annotation.*;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.*;
import tech.qiantong.qdata.common.core.domain.BaseEntity;
import tech.qiantong.qdata.module.da.controller.admin.assetchild.theme.vo.DaAssetThemeRelRespVO;

import java.util.List;

/**
 * Data Asset Application DO - DA_ASSET_APPLY
 *
 * @author shu
 * @date 2025-03-19
 */
@Data
@TableName(value = "DA_ASSET_APPLY")
// Used for auto-increment primary keys in Oracle, PostgreSQL, Kingbase, DB2, H2 databases. Not needed for MySQL and similar databases.
// @KeySequence("DA_ASSET_APPLY_seq")
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
public class DaAssetApplyDO extends BaseEntity {
    @TableField(exist = false)
    private static final long serialVersionUID = 1L;

    /** ID */
    @TableId(type = IdType.AUTO)
    private Long id;

    /** Asset ID */
    private Long assetId;

    /** Asset Category */
    @TableField(exist = false)
    private String assetName;

    /** Asset English Name */
    @TableField(exist = false)
    private String assetTableName;

    /** Asset Category */
    @TableField(exist = false)
    private String catAssetName;

    /** Asset Category Code */
    @TableField(exist = false)
    private String catAssetCode;

    /** Whether the asset is from an application or self-generated by the project. 0: applied, 1: self-created */
    private String sourceType;

    /** Project ID */
    private Long projectId;

    /** Project Name */
    @TableField(exist = false)
    private String projectName;

    /** Project Code */
    private String projectCode;

    /** Theme Name */
    @TableField(exist = false)
    private String themeName;

    @TableField(exist = false)
    private List<DaAssetThemeRelRespVO> daAssetThemeRelList;

    /** Application Reason */
    private String applyReason;

    /** Approval Reason */
    private String approvalReason;

    /** Status */
    private String status;

    /** Valid Flag */
    private Boolean validFlag;

    /** Delete Flag */
    @TableLogic
    private Boolean delFlag;

    /** Datasource Name */
    @TableField(exist = false)
    private String datasourceName;

    /** Datasource IP */
    @TableField(exist = false)
    private String datasourceIp;

    /** Datasource Type */
    @TableField(exist = false)
    private String datasourceType;

    /** Asset Description */
    @TableField(exist = false)
    private String description;

    /** Phone Number */
    @TableField(exist = false)
    private String phonenumber;

    @TableField(exist = false)
    private String type;

}
